apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-anubis-key
stringData:
    ED25519_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:x82VR512QLZflgm29AQdypBtF+TDpUP/P5VlCFxz7jf1wp/nf0JzaUkSqRTY7CAeNuG0SPK04NoaNGGh0+geow==,iv:yiHl4APkwK5Ze5GNCt8CWOeYqd1S9nmTbfL2eY2mdQg=,tag:xtQzxpNI8WScLaWTupGOhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvKzdyU083MjkzM1gxeWlk
            cGZ5SFZPLyttM0RRL2pxYVY0S1RTckkwK0RzCkdWbkM3WUhEc3ZhYTl1MktvaUdU
            aGU5ZU5jcnNzSEhRbVh2NzRJQWRlYXcKLS0tIE1XbmRob1g3djFMckNucUxEUmky
            RTh1dlpEVTlkd0xkb1hhVkw5eFhHc1kKi4RnpW6+aS7oVo6Xsd85rh74ZnDi9y10
            8kSNhqU39uesK2FXe94RndNmbjUBpzW6fGxkXtG58/nACF+mUcnIrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T20:51:30Z"
    mac: ENC[AES256_GCM,data:z2vbMKEYF0biF1iH9ebRLad/HRjy/EH3I5zBGxoH+dCNp4Payusw+v59FlvpHrc3+q9ImR/Ip7yQECCXZSU3n+9g3kFekgp07cql1upUHwE3uWl0dAmJ1/zubFPKvFv+y8I2Ra8GeqVKBnlzus1c3gZJMb/U7X3SNjk/h0L8nRw=,iv:vqUrEm6cBQQVGG1xF6YfVFkY28DvMSRJg08Schjg2Po=,tag:HvR52tC4ox7hwgV12MQ8QA==,type:str]
    version: 3.13.1
