apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-anubis-key-secret
stringData:
    ED25519_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:x82VR512QLZflgm29AQdypBtF+TDpUP/P5VlCFxz7jf1wp/nf0JzaUkSqRTY7CAeNuG0SPK04NoaNGGh0+geow==,iv:yiHl4APkwK5Ze5GNCt8CWOeYqd1S9nmTbfL2eY2mdQg=,tag:xtQzxpNI8WScLaWTupGOhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvKzdyU083MjkzM1gxeWlk
            cGZ5SFZPLyttM0RRL2pxYVY0S1RTckkwK0RzCkdWbkM3WUhEc3ZhYTl1MktvaUdU
            aGU5ZU5jcnNzSEhRbVh2NzRJQWRlYXcKLS0tIE1XbmRob1g3djFMckNucUxEUmky
            RTh1dlpEVTlkd0xkb1MhVkw5eFhHc1kKi4RnpW6+aS7oVo6Xsd85rh74ZnDi9y10
            8kSNhqU39uesK2FXe94RndNmbjUBpzW6fGxkXtG58/nACF+mUcnIrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T21:21:56Z"
    mac: ENC[AES256_GCM,data:hNai72ldg/Ws7IRFAPoXJnmrwQZj7tFPsBPkogGbLTgGilAfRiJBVLKMrvYIys85dkpuy4ZmO8N/1GftX5/+bzgKB25WRdMXzMQMfBgYwjz5HQLzVH/+bYDCdjTtR7sf7tIPd/aHyiV0TqQuAnz8boxWKIzE+D5Ve6TMmxpIzeg=,iv:+61s5FaFuaDBxvaIWCJ1URCd7PG+ykxqVxF7J7I05W4=,tag:dNVUy5fDsy7Kq1KbbxdFcw==,type:str]
    version: 3.13.1
