apiVersion: v1
kind: Secret
metadata:
    name: paperless-db-owner
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Y7oCA7QiHWaa,iv:++BpAzsn03vWG/nYEdWeD39g7UaJ+7QO0dev343rM0s=,tag:SWb78pjwVgk9yEmPsPzgbg==,type:str]
    password: ENC[AES256_GCM,data:17EwKzLFAK92iBA/mDZ4WCl6uhrg06CVUkBjH3mq2re1682S7JMTAAq/OmsTpA==,iv:J8T38pAvt7AvVBzKf4/j8AXDv3rtGVYf5WQ99FI/2Vs=,tag:5fh4pQbQaYIvWOYHmyg+Jg==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvKzdyU083MjkzM1gxeWlk
            cGZ5SFZPLyttM0RRL2pxYVY0S1RTckkwK0RzCkdWbkM3WUhEc3ZhYTl1MktvaUdU
            aGU5ZU5jcnNzSEhRbVh2NzRJQWRlYXcKLS0tIE1XbmRob1g3djFMckNucUxEUmky
            RTh1dlpEVTlkd0xkb1hhVkw5eFhHc1kKi4RnpW6+aS7oVo6Xsd85rh74ZnDi9y10
            8kSNhqU39uesK2FXe94RndNmbjUBpzW6fGxkXtG58/nACF+mUcnIrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T20:35:28Z"
    mac: ENC[AES256_GCM,data:EAWwFoDuVmF/YOPCpfFp0nNsBbu62uan0zNyMKF2bjVl3byNcHhxJfpwF4fBvF50tinnv8BrDurwMYHPNept61sr0AShyTLYYTYqt9ffto45dtt0DHcty14UWW9Q4bpRKzTYAWnuq6YGrJt/aVahsKSdBYhvpckKs+DENglA9jc=,iv:fbHY8NgdFqjhZy5Jd2WKpowaivFZFougoEJFoHZGpRs=,tag:3Fi/cEJfBW+OXLtbWGOH/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
