apiVersion: v1
kind: Secret
metadata:
    name: opencloud-secret
    namespace: selfhosted
stringData:
    idm-admin-password: ENC[AES256_GCM,data:3AjYoj1HRsBL/nh0EIsMUQbUGKXR3Xk6fuP4XnKr0Cah38uGKWlZ6CridFEidlmHCjTENwfU,iv:F/5c0aTbMuaE3iLfPoSWXA5MR1BSKNkVx7k9S7hesfQ=,tag:DV3Tz1xqC2RwNjvUUNq5Aw==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZmVtMjRaSWV4cHZEbWE0
            UmFKYVZPakZ3aDZuMENtSEttT2dHL0ZBNVNFCjY0R2U3Z0pqOXVGb2hjK1VJajN6
            N1Q4NXlnby8vNzNVZWpGeTdlM1lEVUEKLS0tIHJxcE9HM0JoMU9MdDVibXB1dk5u
            ZjNaYzRNWHZRMmJxTjJtVEt4NUlFWWMKdDQPmn5k1QuEYSDS8IyAdPiRO8myUYyi
            P5UdeRzSJlkwgURcLgm6C/BIB0Z8asSyK/sijuCiCsB6AIWvbmtBSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T10:13:07Z"
    mac: ENC[AES256_GCM,data:6iOeDH/kYx/coEzMkHwfS00WChU+6U3P5Xj4FHX85yLSqHe6DgmG6a4/xOMjGtu8xDQWUqbn19H9WIJi3UraSx4SoG3OpK6jKznPRUYfw75tuh//dOS3bO/ZNQYPHWqksyfhl2w9xXbhEo/ZbNYPrTYdPePhiG7/ziQ+JNnGaiw=,iv:UOBUDNJWCo+r0Cx9M0NjYTuhKGmrPUYediuaJSiipwo=,tag:+B+nbALoNgr4jflggu4YXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
