apiVersion: v1
kind: Secret
metadata:
    name: opencloud-secret
    namespace: selfhosted
stringData:
    idm-admin-password: ENC[AES256_GCM,data:3AjYoj1HRsBL/nh0EIsMUQbUGKXR3Xk6fuP4XnKr0Cah38uGKWlZ6CridFEidlmHCjTENwfU,iv:F/5c0aTbMuaE3iLfPoSWXA5MR1BSKNkVx7k9S7hesfQ=,tag:DV3Tz1xqC2RwNjvUUNq5Aw==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZmVtMjRaSWV4cHZEbWE0
            UmFKYVZPakZ3aDZuMENtSEttT2dHL0ZBNVNFCjY0R2U3Z0pqOXVGb2hjK1VJajN6
            N1Q4NXlnby8vNzNVZWpGeTdlM1lEVUEKLS0tIHJxcE9HM0JoMU9MdDVibXB1dk5u
            ZjNaYzRNWHZRMmJxTjJtVEt4NUlFWWMKdDQPmn5k1QuEYSDS8IyAdPiRO8myUYyi
            P5UdeRzSJlkwgURcLgm6C/BIB0Z8asSyK/sijuCiCsB6AIWvbmtBSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-29T20:49:20Z"
    mac: ENC[AES256_GCM,data:HmKOOp3/wE/u3msiqxgAuHaULGTuYAKWsbgJANr30T63sXOtrn4cprH2eT0+HJvZ7ZHoexGEceiYJAIx8RhPI7HLVdRjbdUx2WoRGudYcemWrIjr0luxQ/7yHT+OTP+CQuA3TxIl5HBawCeN9i/cI016Yv++SgAe8Fnl2fqoREc=,iv:h6s+tWxECbnOH+L3A4nyecMeWXj5TS20TtBrUihJznw=,tag:SuqXe7GHvQUI8K+6HtCHYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
