apiVersion: v1
kind: Secret
metadata:
    name: opencloud-secret
    namespace: selfhosted
stringData:
    idm-admin-password: ENC[AES256_GCM,data:kxUb/hnR29KJsJTmZ/7TJP54kWWOXw9pUtNgJqGqbPgMkrs=,iv:8Nj5fK6+aSFA2y7oJl2/AglJcYCpp/e2K4MiOsjLtK4=,tag:uHsGoKDg3KQMaWqPBohn0g==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZmVtMjRaSWV4cHZEbWE0
            UmFKYVZPakZ3aDZuMENtSEttT2dHL0ZBNVNFCjY0R2U3Z0pqOXVGb2hjK1VJajN6
            N1Q4NXlnby8vNzNVZWpGeTdlM1lEVUEKLS0tIHJxcE9HM0JoMU9MdDVibXB1dk5u
            ZjNaYzRNWHZRMmJxTjJtVEt4NUlFWWMKdDQPmn5k1QuEYSDS8IyAdPiRO8myUYyi
            P5UdeRzSJlkwgURcLgm6C/BIB0Z8asSyK/sijuCiCsB6AIWvbmtBSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T09:51:32Z"
    mac: ENC[AES256_GCM,data:2M7DYjlTIfvrU2Q+Kjlsbi6eX7AsZ61epD8Is2+wb+XeLapgTUAkp6rEJKSuWLlik73wCAwD4fM1WTex0IQVqt15TAa0FzqmPd74VSJYFM35glSMwwL6AJNlTUrfU7qgGcm04tBCxFbNjvyQkDbKid0EDmk43IAfZP+/yOjmAbg=,iv:685D6O28fTz8ARyWo1WvkQEEiuJFE1vK8iNPEdEFDb0=,tag:AaJpG0pyfRR1/a+8ALYGyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
