---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "hcloud-public-certificate"
spec:
  dnsNames:
    - "files.${PUBLIC_DOMAIN}"
    - "it-tools.${PUBLIC_DOMAIN}"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: "hcloud-public-certificate"