---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: forgejo
  values:
    strategy:
      type: 'Recreate'
      
    httpRoute:
      enabled: true
      hostnames: [ "code.${CLUSTER_DOMAIN}" ]
      parentRefs:
        - name: envoy-external
          namespace: network
          sectionName: https
    image:
      rootless: true
      registry: code.forgejo.org
      repository: forgejo/forgejo
      tag: 15.0.0-rootless
    persistence:
      enabled: true
      create: false
      claimName: forgejo-code-local
      storageClass: openebs-hostpath
    gitea:
      admin:
        existingSecret: gitea-admin-secret
        passwordMode: keepUpdated
      ssh:
        logLevel: INFO
      config:
        cache:
          ENABLED: true
          ADAPTER: redis
          HOST: redis://forgejo-redis:6379
        cron.archive_cleanup:
          ENABLED: true
          RUN_AT_START: true
          SCHEDULE: "@every 1h"
          OLDER_THAN: 2h
        indexer:
          ISSUE_INDEXER_TYPE: bleve
          REPO_INDEXER_ENABLED: true
        lfs:
          PATH: /data/git/lfs
        server:
          ROOT_URL: https://code.albdev.cloud
          DOMAIN: code.albdev.cloud
          SSH_DOMAIN: code.albdev.cloud
          LFS_START_SERVER: true
        repository:
          DEFAULT_REPO_UNITS: repo.code,repo.releases,repo.issues,repo.pulls,repo.actions
          DISABLED_REPO_UNITS: repo.ext_wiki,repo.ext_issues
          ROOT: /data/git/repositories
        repository.pull-request:
          DEFAULT_DELETE_BRANCH_AFTER_MERGE: true
          DEFAULT_MERGE_STYLE: squash
        service:
          DEFAULT_KEEP_EMAIL_PRIVATE: true
          ENABLE_NOTIFY_MAIL: true
          ALLOW_ONLY_EXTERNAL_REGISTRATION: false
          DEFAULT_ALLOW_CREATE_ORGANIZATION: false
          MAX_CREATION_LIMIT: 100
          DISABLE_REGISTRATION: true
        admin:
          SEND_NOTIFICATION_EMAIL_ON_NEW_USER: true
        mailer:
          ENABLED: false
        database:
          PATH: /data/gitea.db
          DB_TYPE: sqlite3
          SQLITE_JOURNAL_MODE: wal
        session:
          PROVIDER: redis
          PROVIDER_CONFIG: redis://forgejo-redis:6379
        webhook:
          ALLOWED_HOST_LIST: "*"
