apiVersion: v1
kind: Secret
metadata:
    name: gitea-admin-secret
    namespace: development
stringData:
    username: ENC[AES256_GCM,data:Km3FbiCKKR16UP8=,iv:R8wKIYmc/gspL54EUjAopWyyo+90LEYY34rwwBfps+4=,tag:7Oe/WxfBlof3bdDQz+mlRg==,type:str]
    password: ENC[AES256_GCM,data:I1Hasi+U6CrL2Fkdcq0TIpnZo8fBLVD2vWgPcgEizLW1Cwo=,iv:QwB3zxGIfLMDEBwPQk3HsPQlaBht+Gpnwwd6XG+stX4=,tag:gmmRDKF33nebocLEOHvyyw==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZmVtMjRaSWV4cHZEbWE0
            UmFKYVZPakZ3aDZuMENtSEttT2dHL0ZBNVNFCjY0R2U3Z0pqOXVGb2hjK1VJajN6
            N1Q4NXlnby8vNzNVZWpGeTdlM1lEVUEKLS0tIHJxcE9HM0JoMU9MdDVibXB1dk5u
            ZjNaYzRNWHZRMmJxTjJtVEt4NUlFWWMKdDQPmn5k1QuEYSDS8IyAdPiRO8myUYyi
            P5UdeRzSJlkwgURcLgm6C/BIB0Z8asSyK/sijuCiCsB6AIWvbmtBSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T21:24:13Z"
    mac: ENC[AES256_GCM,data:w+UeBl2yF4X2UpgBjjgBs47lnL3UNpMusOU50DBXcwGrYgxMP34lP6xlsO/E/TTSy90JwYFKxWuMIlr3ud9GVnergRrEyu1DACmcvmFUl5sU3VxW5XYidHJvH4geBqMk8dWlBXZxM7LHN/e2CgARuP4wf7pU2tlmpjfoXqIahrQ=,iv:WLmJ7sL66Oqd0K+/dY0kg7gWozMdH97pkwE/Gaib/7M=,tag:akVFMdUo14XUIBusRi2Svw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: development
stringData:
    RUNNER_TOKEN: ENC[AES256_GCM,data:DtIYGfBvhxKj3k0DEZHD+ZwuM1AWhWtYODXY3gEB5WrzVqTN5VcUYg==,iv:GKE+N70Sl0M/0OCGxhUlQG5lFFKUDR6aVteFBmu8gl8=,tag:GMaJi+b/EOqDlhYO+q7f0Q==,type:str]
    FORGEJO_INSTANCE_URL: ENC[AES256_GCM,data:OKW1JpTqWtnifeAV0RHIunKcuLAGjFzk,iv:0pX+1NGkdH8VALEWj9IXRTjjx+cOC0Vv0u4emGtyh6s=,tag:psoNPhn6bOZLTLt5W1SzUA==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZmVtMjRaSWV4cHZEbWE0
            UmFKYVZPakZ3aDZuMENtSEttT2dHL0ZBNVNFCjY0R2U3Z0pqOXVGb2hjK1VJajN6
            N1Q4NXlnby8vNzNVZWpGeTdlM1lEVUEKLS0tIHJxcE9HM0JoMU9MdDVibXB1dk5u
            ZjNaYzRNWHZRMmJxTjJtVEt4NUlFWWMKdDQPmn5k1QuEYSDS8IyAdPiRO8myUYyi
            P5UdeRzSJlkwgURcLgm6C/BIB0Z8asSyK/sijuCiCsB6AIWvbmtBSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T21:24:13Z"
    mac: ENC[AES256_GCM,data:w+UeBl2yF4X2UpgBjjgBs47lnL3UNpMusOU50DBXcwGrYgxMP34lP6xlsO/E/TTSy90JwYFKxWuMIlr3ud9GVnergRrEyu1DACmcvmFUl5sU3VxW5XYidHJvH4geBqMk8dWlBXZxM7LHN/e2CgARuP4wf7pU2tlmpjfoXqIahrQ=,iv:WLmJ7sL66Oqd0K+/dY0kg7gWozMdH97pkwE/Gaib/7M=,tag:akVFMdUo14XUIBusRi2Svw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
data:
    signing_key: ENC[AES256_GCM,data:0Kw+JqRk2S/Xjx5DoVobl/HnJc6ne5RXVsgvt4SvXgahqQ9on06GGqJs9HhMzgYRANlx19MOSz4B5cWdfed/kiDJNTfExLkREYsocnWqr6I6MyqPILljgwvgX/YH0R1E7oJfHC0uZ6Xk90Yn88YBGVkJvkZ/Bx2Oa7cHU0rOsb4sPWzVqX3UnfCkhUCzbH3Zl7TG4Kpu6A2xXFDmVb1WVYAIn2HVFqZeuU8z/jl8iRLOggv5eNdQxSw3YiU2eMVMcChK9t4U9iuKnrKHL3I59o7orvX2ft8RXO7eEqXF0QsgWedZcBKpQvrPw1W27ZSu03A5yPTH+nd46tcLPEbL7ksE6aYi/LFIz5BtxCXV6Gc1kH36jJnI2b/BAN8iovQi+2gK6Bp5m37438Jn+I/fkVKJ76jxHuUnUvQqnhNJRJl+Zt2hraSgx8X4SqSuGhjujTuuZj9UxLIRHUpLjpPpZUz14/PPGNjgLP7+NpwEQFN9/pYkB2BGOZ/AdNpJ1nbp44+O/5+6/skir/VD8prUekzqMch7sqlmrN4UysnkV7qltj1pyCKdL9dsA0BiwT7OP18GHz+XOvp5zgLRXcjb0sepC8h+Mi9Ru98z5eN5oeciiboWBInFq69OhFtdYk0yU3R4XrAPMmlscQQm9TOLNwAa+PktoHptAAH+9P/QnVxgkJPND6sOlO1U/JxtB2yXmTNvf3cHf/e6nDP/xfQ260HbytE=,iv:fd1hMykYrfLEyW9dH1qjrYcTWl6HVCTsHS3jlz6GAa0=,tag:7NNi9nUJR+6JPOXUlGBRGg==,type:str]
    signing_key.pub: ENC[AES256_GCM,data:brOwbQQ60H8Qvqeex2rq1naRc26C+JMWJRAKNObNdEfAvNQg2lP+rMsEVVOA6LeaRduFy9sqwLR22gP9HtpK2hCd4lfndb+wYELTOnsa8FPXl2Jb1Kpj/N9ZSrvsXL0GmTNzXzLt5CvLi5JpP2RPO6AkzLZQXH5+zGlwUmMaAcQ8/6D7,iv:ps4iY2T6AN6hNV+Gsdtu8LL6Da+ImyKVCnwW4DZvLfI=,tag:VZlwUsJJYpwMkrzNhB/nLA==,type:str]
metadata:
    name: forgejo-signing-key
    namespace: development
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZmVtMjRaSWV4cHZEbWE0
            UmFKYVZPakZ3aDZuMENtSEttT2dHL0ZBNVNFCjY0R2U3Z0pqOXVGb2hjK1VJajN6
            N1Q4NXlnby8vNzNVZWpGeTdlM1lEVUEKLS0tIHJxcE9HM0JoMU9MdDVibXB1dk5u
            ZjNaYzRNWHZRMmJxTjJtVEt4NUlFWWMKdDQPmn5k1QuEYSDS8IyAdPiRO8myUYyi
            P5UdeRzSJlkwgURcLgm6C/BIB0Z8asSyK/sijuCiCsB6AIWvbmtBSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T21:24:13Z"
    mac: ENC[AES256_GCM,data:w+UeBl2yF4X2UpgBjjgBs47lnL3UNpMusOU50DBXcwGrYgxMP34lP6xlsO/E/TTSy90JwYFKxWuMIlr3ud9GVnergRrEyu1DACmcvmFUl5sU3VxW5XYidHJvH4geBqMk8dWlBXZxM7LHN/e2CgARuP4wf7pU2tlmpjfoXqIahrQ=,iv:WLmJ7sL66Oqd0K+/dY0kg7gWozMdH97pkwE/Gaib/7M=,tag:akVFMdUo14XUIBusRi2Svw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
