apiVersion: v1
kind: Secret
metadata:
    name: gitea-admin-secret
    namespace: development
stringData:
    username: ENC[AES256_GCM,data:Km3FbiCKKR16UP8=,iv:R8wKIYmc/gspL54EUjAopWyyo+90LEYY34rwwBfps+4=,tag:7Oe/WxfBlof3bdDQz+mlRg==,type:str]
    password: ENC[AES256_GCM,data:I1Hasi+U6CrL2Fkdcq0TIpnZo8fBLVD2vWgPcgEizLW1Cwo=,iv:QwB3zxGIfLMDEBwPQk3HsPQlaBht+Gpnwwd6XG+stX4=,tag:gmmRDKF33nebocLEOHvyyw==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZmVtMjRaSWV4cHZEbWE0
            UmFKYVZPakZ3aDZuMENtSEttT2dHL0ZBNVNFCjY0R2U3Z0pqOXVGb2hjK1VJajN6
            N1Q4NXlnby8vNzNVZWpGeTdlM1lEVUEKLS0tIHJxcE9HM0JoMU9MdDVibXB1dk5u
            ZjNaYzRNWHZRMmJxTjJtVEt4NUlFWWMKdDQPmn5k1QuEYSDS8IyAdPiRO8myUYyi
            P5UdeRzSJlkwgURcLgm6C/BIB0Z8asSyK/sijuCiCsB6AIWvbmtBSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T16:31:32Z"
    mac: ENC[AES256_GCM,data:1TkHljdGDDntJMgYf9Hw+KFffRIQccQV6Siiylv0eQRCnkT+8CevMnHWAO4mOYIY8VG1T5/FELWLwSJvMd1YogbWBN6gqKLkK7I5bCcWCWN0GIK+alfm5MhQ9EagshJbI7ohzgTFK660Dvoa5fmRpUhRrFQm6zNGz2LBPaf54v0=,iv:1sOynR8/VsG5Khxwpawl6W5jNbVR1f04Q6x7uftLd7A=,tag:FYz2CUTEWZi/wiWmXa42uw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: development
stringData:
    RUNNER_TOKEN: ENC[AES256_GCM,data:DtIYGfBvhxKj3k0DEZHD+ZwuM1AWhWtYODXY3gEB5WrzVqTN5VcUYg==,iv:GKE+N70Sl0M/0OCGxhUlQG5lFFKUDR6aVteFBmu8gl8=,tag:GMaJi+b/EOqDlhYO+q7f0Q==,type:str]
    FORGEJO_INSTANCE_URL: ENC[AES256_GCM,data:OKW1JpTqWtnifeAV0RHIunKcuLAGjFzk,iv:0pX+1NGkdH8VALEWj9IXRTjjx+cOC0Vv0u4emGtyh6s=,tag:psoNPhn6bOZLTLt5W1SzUA==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZmVtMjRaSWV4cHZEbWE0
            UmFKYVZPakZ3aDZuMENtSEttT2dHL0ZBNVNFCjY0R2U3Z0pqOXVGb2hjK1VJajN6
            N1Q4NXlnby8vNzNVZWpGeTdlM1lEVUEKLS0tIHJxcE9HM0JoMU9MdDVibXB1dk5u
            ZjNaYzRNWHZRMmJxTjJtVEt4NUlFWWMKdDQPmn5k1QuEYSDS8IyAdPiRO8myUYyi
            P5UdeRzSJlkwgURcLgm6C/BIB0Z8asSyK/sijuCiCsB6AIWvbmtBSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T16:31:32Z"
    mac: ENC[AES256_GCM,data:1TkHljdGDDntJMgYf9Hw+KFffRIQccQV6Siiylv0eQRCnkT+8CevMnHWAO4mOYIY8VG1T5/FELWLwSJvMd1YogbWBN6gqKLkK7I5bCcWCWN0GIK+alfm5MhQ9EagshJbI7ohzgTFK660Dvoa5fmRpUhRrFQm6zNGz2LBPaf54v0=,iv:1sOynR8/VsG5Khxwpawl6W5jNbVR1f04Q6x7uftLd7A=,tag:FYz2CUTEWZi/wiWmXa42uw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
