apiVersion: v1
kind: Secret
metadata:
    name: gitea-admin-secret
    namespace: development
stringData:
    username: ENC[AES256_GCM,data:Km3FbiCKKR16UP8=,iv:R8wKIYmc/gspL54EUjAopWyyo+90LEYY34rwwBfps+4=,tag:7Oe/WxfBlof3bdDQz+mlRg==,type:str]
    password: ENC[AES256_GCM,data:I1Hasi+U6CrL2Fkdcq0TIpnZo8fBLVD2vWgPcgEizLW1Cwo=,iv:QwB3zxGIfLMDEBwPQk3HsPQlaBht+Gpnwwd6XG+stX4=,tag:gmmRDKF33nebocLEOHvyyw==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZmVtMjRaSWV4cHZEbWE0
            UmFKYVZPakZ3aDZuMENtSEttT2dHL0ZBNVNFCjY0R2U3Z0pqOXVGb2hjK1VJajN6
            N1Q4NXlnby8vNzNVZWpGeTdlM1lEVUEKLS0tIHJxcE9HM0JoMU9MdDVibXB1dk5u
            ZjNaYzRNWHZRMmJxTjJtVEt4NUlFWWMKdDQPmn5k1QuEYSDS8IyAdPiRO8myUYyi
            P5UdeRzSJlkwgURcLgm6C/BIB0Z8asSyK/sijuCiCsB6AIWvbmtBSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T21:22:08Z"
    mac: ENC[AES256_GCM,data:mBP7jT3ERd43+/sSf16x27NI8IUikQVnGxwOg7VnKzmfgJO2jYmADA4iXwKR9268dyCxgNX9CBGsPHxpShcOT28hQ4MTe8v2Zd4ks6PeIe7ohCPu6eWhRYZ+ppykgsxN8qUgM7EfLd+M6ZZ9bYJSRSXY2qWmhuqw7wjtXyLH8Nk=,iv:W0KV465wiWFXDeuP3CJRj+19A6EnhW+vwytsBlY1xZE=,tag:M4ersss7NYn/TpoHfch0Kg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: development
stringData:
    RUNNER_TOKEN: ENC[AES256_GCM,data:DtIYGfBvhxKj3k0DEZHD+ZwuM1AWhWtYODXY3gEB5WrzVqTN5VcUYg==,iv:GKE+N70Sl0M/0OCGxhUlQG5lFFKUDR6aVteFBmu8gl8=,tag:GMaJi+b/EOqDlhYO+q7f0Q==,type:str]
    FORGEJO_INSTANCE_URL: ENC[AES256_GCM,data:OKW1JpTqWtnifeAV0RHIunKcuLAGjFzk,iv:0pX+1NGkdH8VALEWj9IXRTjjx+cOC0Vv0u4emGtyh6s=,tag:psoNPhn6bOZLTLt5W1SzUA==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZmVtMjRaSWV4cHZEbWE0
            UmFKYVZPakZ3aDZuMENtSEttT2dHL0ZBNVNFCjY0R2U3Z0pqOXVGb2hjK1VJajN6
            N1Q4NXlnby8vNzNVZWpGeTdlM1lEVUEKLS0tIHJxcE9HM0JoMU9MdDVibXB1dk5u
            ZjNaYzRNWHZRMmJxTjJtVEt4NUlFWWMKdDQPmn5k1QuEYSDS8IyAdPiRO8myUYyi
            P5UdeRzSJlkwgURcLgm6C/BIB0Z8asSyK/sijuCiCsB6AIWvbmtBSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T21:22:08Z"
    mac: ENC[AES256_GCM,data:mBP7jT3ERd43+/sSf16x27NI8IUikQVnGxwOg7VnKzmfgJO2jYmADA4iXwKR9268dyCxgNX9CBGsPHxpShcOT28hQ4MTe8v2Zd4ks6PeIe7ohCPu6eWhRYZ+ppykgsxN8qUgM7EfLd+M6ZZ9bYJSRSXY2qWmhuqw7wjtXyLH8Nk=,iv:W0KV465wiWFXDeuP3CJRj+19A6EnhW+vwytsBlY1xZE=,tag:M4ersss7NYn/TpoHfch0Kg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
data:
    signing_key: ENC[AES256_GCM,data:yMibLB88MfrQ394QqEi502P9ClslYTcH8H0qmGEGJPFGctoS/igJlIc2YU4UnSMTZK1ns8aCxTRGHi3Yw7VB0xOntKdNwWCdPOvhfHLCvIDxTCd/QoJZymQQSUjBRm3TM3UGt0pUR/m+vyTYL6eSdCPHbcafS3WOOIpySvq98tOILu4cbgOdLeCsyaph5s3XVqOK/J05mmJgGBLY72hRQDLk2G82nGIVSgcvGwFnw446V4bRZHfFJ9aGgBGJ0jib9NxneIel8xQc6Khl4QmjzozJUxWDGdE+MLeNtcWmRu/sgOGqJ1ZMqBN6u2Mv9ICdPKYhKixiFfAx+RjUFjIkIG+cWsAZr7ARUcnULwKpPw07BjfMabB+CvD7KO90aAmuv5cdp81drPBhxEEiMf9Av03ppm9syTYHGa999Mhl692x7+u49UKoBBuG7DruPF5A+Vs4WX1zOEc8TjQMPyB3y1/RE9Bb/d73pCAZq9d4FQAEKD4F4hUJoVlGUrh6/QSrMUOJbYBJTZqpsHw2exjinRCUUgbnUEjSIkWKKLqpHMGVYE7e/byh0DaEOlwsBETrkEfU3i46ayQ3thhUUNygq5sP3uWHpytAWyPp1YeOiELJm/qLQWza9PHV3yL7npEp55vgYnpMUpkhvvBlL4hmsIpp/LoUeiEkBNHNwNyJvn/v6AKM4rlhwtMArHSw42A7vhE9KyB2xsv0N6hlq40k86oAztU=,iv:Dvb//5QnL/y+1N3EPjI79za9momT9kuFPm1Zwr69v70=,tag:P0BtcH7jgT95YIqhk9+ZIw==,type:str]
    signing_key.pub: ENC[AES256_GCM,data:zr/kDoW9AfXs2u2R0nEmAxpLKu1CkbUkn3OpZM+oemdvkZ+Tpy/Vh/jEfUA24yYLVadiuWIiOl1gxYCJytA3F0v8yOfc6ESBgkWh6QF13SZ0W8fR8IJ/Wj9HKOt2yqIs87bGQPAKDvhDEZDt62aMaReUTc27BjbThN5ZCGhxlaKVKX/W,iv:4UpuV6/XbyLEZF/qdxT/VmkYajRSKsyjwpfqtot6NxE=,tag:fZ7sD3/PZMeYi+vqjhcpXw==,type:str]
metadata:
    name: forgejo-signing-key
    namespace: development
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZmVtMjRaSWV4cHZEbWE0
            UmFKYVZPakZ3aDZuMENtSEttT2dHL0ZBNVNFCjY0R2U3Z0pqOXVGb2hjK1VJajN6
            N1Q4NXlnby8vNzNVZWpGeTdlM1lEVUEKLS0tIHJxcE9HM0JoMU9MdDVibXB1dk5u
            ZjNaYzRNWHZRMmJxTjJtVEt4NUlFWWMKdDQPmn5k1QuEYSDS8IyAdPiRO8myUYyi
            P5UdeRzSJlkwgURcLgm6C/BIB0Z8asSyK/sijuCiCsB6AIWvbmtBSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T21:22:08Z"
    mac: ENC[AES256_GCM,data:mBP7jT3ERd43+/sSf16x27NI8IUikQVnGxwOg7VnKzmfgJO2jYmADA4iXwKR9268dyCxgNX9CBGsPHxpShcOT28hQ4MTe8v2Zd4ks6PeIe7ohCPu6eWhRYZ+ppykgsxN8qUgM7EfLd+M6ZZ9bYJSRSXY2qWmhuqw7wjtXyLH8Nk=,iv:W0KV465wiWFXDeuP3CJRj+19A6EnhW+vwytsBlY1xZE=,tag:M4ersss7NYn/TpoHfch0Kg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
