apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:yQb4D5lL0BkxndbpFA==,iv:YcRUiSD0NUp0odP9VtkfX8gjmnWzFaY+I64GRNenxXc=,tag:MVxD28DrpI9BO4od79KHMg==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:aK6200tiD7+LeZ2t5cFbIqkk++TQmjG3eAM3w6x4HblhN45iGTU4alI=,iv:rmR3+Y8dCIFU9kssuZlHUsDmw/Ys1aIeHTZPFEMJWuo=,tag:wJhim9et5BweKmjgTm1AjA==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:MUVqrbIO4ARdwBF9qDL9,iv:Mh0ltJZaePYqaVYKgFW1ZFwGYuxg+rRxrs66OUQmu8E=,tag:/fXwX03snQSM4HpAAqxDHQ==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:ATqOOWgSprCa/RhXBxVpekX2z7n4,iv:+3uXOps7pbBKFBxlBiu4YS7EN5k3TfC0JyKzJ2/dh60=,tag:oXP1vdWuVsWFPc7OmZV6Qw==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvKzdyU083MjkzM1gxeWlk
            cGZ5SFZPLyttM0RRL2pxYVY0S1RTckkwK0RzCkdWbkM3WUhEc3ZhYTl1MktvaUdU
            aGU5ZU5jcnNzSEhRbVh2NzRJQWRlYXcKLS0tIE1XbmRob1g3djFMckNucUxEUmky
            RTh1dlpEVTlkd0xkb1hhVkw5eFhHc1kKi4RnpW6+aS7oVo6Xsd85rh74ZnDi9y10
            8kSNhqU39uesK2FXe94RndNmbjUBpzW6fGxkXtG58/nACF+mUcnIrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T23:40:51Z"
    mac: ENC[AES256_GCM,data:EuUsNTdyaQ+SZHzpfronLxAsg+RAy3ULlE8zbsUJnTlWVnsCXPnrWQEIq2Opp+iRwlH20IZQ9dkDtTc6ei7Y9kXYiMrBXVbUZC9qPxXrUuPiIrDVf+VhXxW1qhiLcdpnVF7XCQ+PUp+bs44/BHe/U3QZ6sJlopT2EdA5kh/He98=,iv:nTUN2ukYIWMpBh7H3n3ceryDkxJFqRDxSPhTKMqBo4E=,tag:xCKyM0eQ/3kZ7vryYh8XGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
