apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:C4p4uYwF7gdvDw==,iv:ZMLu/WoFGebDDJr6c7Lq/UEeU/ziEclR8MpYIN/IQBk=,tag:C3duQz77yszDFxZrNzyh4g==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:aK6200tiD7+LeZ2t5cFbIqkk++TQmjG3eAM3w6x4HblhN45iGTU4alI=,iv:rmR3+Y8dCIFU9kssuZlHUsDmw/Ys1aIeHTZPFEMJWuo=,tag:wJhim9et5BweKmjgTm1AjA==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:MUVqrbIO4ARdwBF9qDL9,iv:Mh0ltJZaePYqaVYKgFW1ZFwGYuxg+rRxrs66OUQmu8E=,tag:/fXwX03snQSM4HpAAqxDHQ==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:ATqOOWgSprCa/RhXBxVpekX2z7n4,iv:+3uXOps7pbBKFBxlBiu4YS7EN5k3TfC0JyKzJ2/dh60=,tag:oXP1vdWuVsWFPc7OmZV6Qw==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvKzdyU083MjkzM1gxeWlk
            cGZ5SFZPLyttM0RRL2pxYVY0S1RTckkwK0RzCkdWbkM3WUhEc3ZhYTl1MktvaUdU
            aGU5ZU5jcnNzSEhRbVh2NzRJQWRlYXcKLS0tIE1XbmRob1g3djFMckNucUxEUmky
            RTh1dlpEVTlkd0xkb1hhVkw5eFhHc1kKi4RnpW6+aS7oVo6Xsd85rh74ZnDi9y10
            8kSNhqU39uesK2FXe94RndNmbjUBpzW6fGxkXtG58/nACF+mUcnIrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T23:25:23Z"
    mac: ENC[AES256_GCM,data:HLYvNwlCqgowh8IoCkLC4FDed3G533VZ0ICJ6rKnkIkWu5SNSlyJOIuWe8BUIupdwZKG5ROgROErXT47EgB9CEfg2QMT+PrZPQxaQRKRkkGvR3IJcWW388Bv5Z0FZl8AZ7f44i5rXk8xvPFLT8kZge3GWVtwVB4QndTDnI9Wy4U=,iv:KCRqaP0cCoO69kWGQ/PYYl/ZfcM+xFpoLDSUouPyWTI=,tag:40oAxxY/PDtS6QrmjJ0P/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
