---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: cert-manager
  values:
    crds:
      enabled: true
    extraArgs:
    - --dns01-recursive-nameservers=root-dns.netcup.net:53
    - --dns01-recursive-nameservers-only
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
    cainjector:
      replicaCount: 1
    podDnsPolicy: "None"
    podDnsConfig:
      nameservers:
      - "root-dns.netcup.net"