---
creation_rules:
  # IMPORTANT: Talos-Regel MUSS ganz oben stehen, sonst greift sie nicht
  - path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa"

  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa"

  - path_regex: bootstrap/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa"

  # for doco-cd: 
  - path_regex: \.enc\.(env|ya?ml|json)$
    key_groups:
      - age:
          - "age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa"