apiVersion: v1
kind: Secret
metadata:
    name: kopiur-repository-secret
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:p6HFicX4DFV52bVLVRS27epiGalkcLD485Wt4kpsaFcI8HyKVOa5juu4PvNF9BUyVUGdj071+IRW/NSDVI4wrw==,iv:3gYPUfuZhcK6o7r/S+rCRdojSwuPib+/Py1KBo9P9FE=,tag:gyDro8mQLk0Uqzxr9KI26A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNTB1MnNaUnZjOXdoUE9D
            NElQS2d4M3F2cFRDbW1Da0dhMXBRMXMyckJFCkF4N0lGNEM2QWtvSVJGM3NsdllN
            V0srNVVzTlhML1ZXRmI2bmw5WnRqUWsKLS0tIFRLTC8yQm1lQmxIdXo1SXFMYnRs
            aWpQakt4VTlzb2Nka0tiUDZiOXUwMTQKFdZiptbnZvXJVvwSy87WHXz1wuKkiOIX
            1ZDyA8bVI93p+/Y/NIrItdN4JuvNVMiBCLzYjMB29x4wirTmCqDNBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T19:10:24Z"
    mac: ENC[AES256_GCM,data:IdbRrtdXeviOU67fjRgCLnJB4wuPczRxCho0UJjJq5OS+jA9dM7UzTlUzGPc60KJZYc+LzpkaihAgsfQY/Hasorj67PJPCM5exYoxMkgQqsfwr1aC0e86orPsU09TXrKq/WBaNnLlHl1Lhp8YGEHMuChIo53F5iR9OU1E9NHr9w=,iv:CxnlLDo8u306T82U0IGDrnTfilZ88FBlRvMhLBxy2No=,tag:H64fJ18fDBbMH2NglRIl7w==,type:str]
    version: 3.13.3
