apiVersion: v1
kind: Secret
metadata:
    name: kopiur-repository-secret
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:p6HFicX4DFV52bVLVRS27epiGalkcLD485Wt4kpsaFcI8HyKVOa5juu4PvNF9BUyVUGdj071+IRW/NSDVI4wrw==,iv:3gYPUfuZhcK6o7r/S+rCRdojSwuPib+/Py1KBo9P9FE=,tag:gyDro8mQLk0Uqzxr9KI26A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:nXuSINkkOth1oCYflpqk5+fNIPE=,iv:22tTU4eEOUU0kL0JJIIAf+g4Z6U7Med4qCeyv9tdC4I=,tag:vYc7cCgh4yCQiOSvF+DwCw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:c4zz4HVonx/2iKWpE26K7abQ7Z8QqRCTTxG2//+6PHl5UfrbSa3iPg==,iv:5rQ1HTK84a08Ac6NDE1E17h6Guj7zvcsuHFJ54iKR7I=,tag:gIoyBxXpFXouopx7UUcYfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNTB1hnNaUnZjOXdoUE9D
            NElQS2d4M3F2cFRDbW1Da0dhMXBRMXMyckJFCkF4N0lGNEM2QWtvSVJGM3NsdllN
            V0srNVVzTlhML1ZXRmI2bmw5WnRqUWsKLS0tIFRLTC8yQm1lQmxIdXo1SXFMYnRs
            aWpQakt4VTlzb2Nka0tiUDZiOXUwMTQKFdZiptbnZvXJVvwSy87WHXz1wuKkiOIX
            1ZDyA8bVI93p+/Y/NIrItdN4JuvNVMiBCLzYjMB29x4wirTmCqDNBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T11:26:14Z"
    mac: ENC[AES256_GCM,data:2T3nvHCm8bPjllVBslYQ/OOZsVhqH7UmAk1ffCiHadNyz3sdgr3PIHb6LbKj/4BY91g5AFnO+gU1tUeJ7gEydu0kUzbFnbwR1aB934LnPcGHBFmtvFIwlu5Y8H/enDwZqAfYMEaqPrhTRANTC7qlHreKAylr3TA4srBm9t4XrgU=,iv:vwvae/jDX25u8CZB8mIWe5SkBMclpw7ShLt48Jp1IkI=,tag:4Bj8xFffNU5Hwa4s7zZGtg==,type:str]
    version: 3.13.3
