---
apiVersion: volsync.backube/v1alpha1
kind: KopiaMaintenance
metadata:
  name: kopia-daily-maintenance
  namespace: volsync
spec:
  repository:
    repository: volsync-kopia-secret
  trigger:
    schedule: "0 5 * * *"
  enabled: true