---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
spec:
  chartRef:
    kind: OCIRepository
    name: pihole
  interval: 15m
  values:
    controllers:
      pihole:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          pihole:
            image:
              repository: ghcr.io/pi-hole/pihole
              tag: 2026.02.0@sha256:ee348529cea9601df86ad94d62a39cad26117e1eac9e82d8876aa0ec7fe1ba27
            env:
              TZ: ${TIMEZONE}
              FTLCONF_dns_listeningMode: all
              FTLCONF_webserver_port: &pihole-port 80
              FTLCONF_dns_upstreams: 127.0.0.1#5335
              FTLCONF_dns_dnssec: true
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            securityContext:
              allowPrivilegeEscalation: false
            resources:
              requests:
                cpu: 100m
              limits:
                # looking at the query log can spike the memory usage very high
                memory: 512Mi
          unbound:
            image:
              repository: alpinelinux/unbound
              tag: latest@sha256:5fe667869deb8904926ea4efcd520a2194ac1eb373faf2b82e75103dddf2f2ab
            securityContext:
              allowPrivilegeEscalation: false
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 512Mi

    service:
      app:
        forceRename: pihole
        controller: pihole
        type: LoadBalancer
        #ipFamilies: [IPv4, IPv6]
        #ipFamilyPolicy: PreferDualStack
        annotations:
          lbipam.cilium.io/ips: 192.168.178.3
        ports:
          dns-udp:
            port: 53
            protocol: UDP
          dns-tcp:
            port: 53
            protocol: TCP
          http:
            primary: true
            port: *pihole-port
            protocol: HTTP
          https:
            port: 443
            protocol: HTTPS

    route:
      app:
        hostnames:
          - '{{ .Release.Name }}.${CLUSTER_DOMAIN}'
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: pihole
                port: 80
        #rules:
        #  - backendRefs: [{ identifier: app }]
        #    sessionPersistence:
        #      sessionName: pihole
        #      type: Cookie
        #      absoluteTimeout: 35m

    persistence:
      config:
        existingClaim: ${VOLSYNC_CLAIM}
        advancedMounts:
          pihole:
            pihole:
              - path: "/etc/pihole"
                subPath: "pihole"
      unbound-config:
        type: configMap
        name: unbound-conf
        advancedMounts:
          pihole:
            unbound:
              - path: "/etc/unbound/unbound.conf"
                subPath: "unbound.conf"
      root-hints:
        type: configMap
        name: root-hints
        advancedMounts:
          pihole:
            unbound:
              - path: "/var/lib/unbound/root.hints"
                subPath: "root.hints"                