apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
stringData:
    FTLCONF_webserver_api_password: ENC[AES256_GCM,data:ywzOJF5ybo8=,iv:v4QHIBFPdelyd9pSXWXYKJdg5wZ82xUyCisWzxjIqRc=,tag:jlNMBe4yFbff/E3z3e6HCA==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvKzdyU083MjkzM1gxeWlk
            cGZ5SFZPLyttM0RRL2pxYVY0S1RTckkwK0RzCkdWbkM3WUhEc3ZhYTl1MktvaUdU
            aGU5ZU5jcnNzSEhRbVh2NzRJQWRlYXcKLS0tIE1XbmRob1g3djFMckNucUxEUmky
            RTh1dlpEVTlkd0xkb1hhVkw5eFhHc1kKi4RnpW6+aS7oVo6Xsd85rh74ZnDi9y10
            8kSNhqU39uesK2FXe94RndNmbjUBpzW6fGxkXtG58/nACF+mUcnIrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T21:34:40Z"
    mac: ENC[AES256_GCM,data:69EUPBbe3HihERMKjwJugVuz/GWiybfel7oUPRhiwLwWlA/qPegSDjP6BpZHDNHsfEkGtw9T8z80t1rXNxrTuKuPADEqUZ8mEW20WU10ey3l3VuD6oOD9C4VbXjSU7CePG6Cop9udJR+r1bdEKcoif+kelsjjvbE711+BqfmavQ=,iv:GpJxW707V5dy61bvydQXxVgpu4V1qZ43QMuzoaNCdho=,tag:XFNacDJH+8S+gHCVNhQQbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
