apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
stringData:
    WEBPASSWORD: ENC[AES256_GCM,data:26oX4TNSOO8=,iv:j4jLSiOYDFybl89IlP7mUdf0Ov9RqTZaiCHltsgGu44=,tag:7SA0eeuj15wmeHom/cGY5A==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvKzdyU083MjkzM1gxeWlk
            cGZ5SFZPLyttM0RRL2pxYVY0S1RTckkwK0RzCkdWbkM3WUhEc3ZhYTl1MktvaUdU
            aGU5ZU5jcnNzSEhRbVh2NzRJQWRlYXcKLS0tIE1XbmRob1g3djFMckNucUxEUmky
            RTh1dlpEVTlkd0xkb1hhVkw5eFhHc1kKi4RnpW6+aS7oVo6Xsd85rh74ZnDi9y10
            8kSNhqU39uesK2FXe94RndNmbjUBpzW6fGxkXtG58/nACF+mUcnIrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T21:04:39Z"
    mac: ENC[AES256_GCM,data:toVcMAY/jH+sHcXTX1Lph4Ns7cMbNROA0vTAjkN37BOQrsWT80mHWg7xTcOg8SKaH9yYaI0M5TVSDgnY3zqxEtLM90dnY1Btlp758smts/s0hY64va6LUfWG5lBCChrtk6E5n5X09IGeynKnaVvtyaTRChu4zxgupn6Jao5jspI=,iv:uu136l1HrQQIKgnH3yeUCg+ndQCD++9TKAXlbzg3E1g=,tag:3usEaK/yzw/y8q8Z00feGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
