---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arrs-config
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 30Gi
  storageClassName: local-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arrs-downloads
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-hostpath