---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arrs-downloads
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-hostpath