apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secret
    namespace: selfhosted
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:P/jd5wR8kw==,iv:KVBz3BZPzplIrQpn5b3dFNAR0x+u4AYAsYOTlbBqBdY=,tag:Wv2GQ/fIJ1GmpDaKRHKXhA==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:h7E4qIwvub19,iv:ypo6YRkWmmxC/2xX/WnzeHSkz5fQIt5LxSAgSG5+a/k=,tag:6S3S5ogS3KGzDF50gVBmzA==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:B7tEiTqf5cTs3idFffc6/uOW78tjoqe1reM7N7A79vtiPGKr+vgSzQKicxg=,iv:tG4c6wVGKso45/X0sbcnyLYWQzV5LpQWaS+COGUnN3s=,tag:seVNhxdZOzFPvUYheWtoaQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:UeIJqiVvGZSURraRKv5M,iv:/7+I+FMwYX5ZKBS8OJ/r0Rca3w7BOmKJKdd5qXbu8nY=,tag:7tGbY86g1QBIZZ6mOSgfzg==,type:str]
    OWNED_ONLY: ENC[AES256_GCM,data:m1/n,iv:wCpcC3DEiGjAMovkVXJKQ9MfnjTIJS7d/2FD0pi3qLs=,tag:tz4k+rlJRfHTZcEPNeqF1g==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:0YsLWjp7ee/iZCg=,iv:GSxk2ss8P9F4QkKWB4k6WF+ei4opymLe21FUcfvzk2w=,tag:B77S5sp4i8y92VOwNM6qBQ==,type:str]
    client-id: ENC[AES256_GCM,data:ytQ+f3c8nNHPbax7MDFHQkb6ruRfnTbxWTaedHvNqDpIbj3L,iv:METI8d5UDENsPcD1+He2Y6Gqmwe25d9i1t98rNUZ0Bg=,tag:89PCNg5MBtFeGQRINN7p6Q==,type:str]
    client-secret: ENC[AES256_GCM,data:LN4aPlfpgmzm0Y0uwdT09PxuJaJDXqj1ISaIdoU4ZQc=,iv:xjBVdGGpVHDxD4Y+GYknK84cLz+WiDUuGrmxhsve/eo=,tag:avwiObbFiTYgsBi4kH5oDA==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGhnZDdjR1VkYWhrRXJx
            SmRtV1plWUNmL2ZlMTNwbGErRVB4SDRLcUI4CkFMQ0NEVStvUUVMR2hnSTdCUHha
            ek1JcEN6U3lDWkFjSCtIem1JdEltYzgKLS0tIHZtYWVweXdsR0hxSmswQ0hnUTRz
            VDNKWlowS1VXZURES0dJMzRQaWRhQ3cKQFvSLEyCn3WbsD+wCbM4OwuSkHrAr3i1
            fYsM2EhWu/knKGh/zYYqzKpDyV+tjPmvjvI8wWpkZ4RFGTVL8WT/rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T22:01:37Z"
    mac: ENC[AES256_GCM,data:cLzgPz7TKi3Q+v3Qb6Za7I/OqfoA2tXAtyKetm7nkQWjWN1G90XepOpMwbsh2BjgNiDXEEMkHaJwdMI8ne1j7B8zy6MGZXz4lbnWSFev8m6fsHrghsaOXPq03UHn7rtkPlIej8So1qZDOymsnL8uomDkXpBCY5vn+XMnETuEiu0=,iv:aLCNI+OYYRQJrjo3wClyhae/q3Wmmrf3CbF+BW5yvF0=,tag:gyjPkViQlXyAE+2HNkHJ0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
