---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-v1
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-hostpath