---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: onji-space-dns
spec:
  secretName: onji-space-production-dns-tls
  issuerRef:
    name: letsencrypt-production-dns
    kind: ClusterIssuer
  commonName: "*.onji.space"
  dnsNames:
    - onji.space
    - "*.onji.space"
    - vpn.onji.space
    - "*.vpn.onji.space"
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always