---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: albdev-tls
spec:
  secretName: albdev-tls
  issuerRef:
    name: letsencrypt-production-dns
    kind: ClusterIssuer
  commonName: albdev.cloud
  dnsNames:
    - albdev.cloud
    - "*.albdev.cloud"
    - onji.space
    - "*.onji.space"
  subject:
    countries: ["DE"]
    organizations: ["albcloud-homeops"]
    provinces: ["NRW"]
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always