apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:XfdwVq4CqQEnuA==,iv:X3ny12B2UTA1pfGjBcZ0eZQeSclsSP6RNTDXU8YBlUk=,tag:xIiVtSObTSCWUSt0fYoOPg==,type:str]
    SECRET_WORK_DOMAIN: ENC[AES256_GCM,data:BZ5HSM3jwME=,iv:a0OVyYWrU1uCInF4XVi2g/xUF3S2luVtXnYGCaouN98=,tag:wbDHxRH2BWQFD6cuHl1OqQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:l6PD3x48RYMaw0dcAvc=,iv:6SASQwwNEpqYbHQQ9thr7EK13l7wx0Lz/yGkCct3hHo=,tag:wzB3LUN5Fbk2st2q04Xk6Q==,type:str]
    VPN_DOMIAN: ENC[AES256_GCM,data:ZfW//s+mNgI2ZXvZRMs=,iv:io3WpmdsYyrfLwfFkBt181hnC4DwZsucZJT6kigyHKg=,tag:+aZY/Sxx3rXDkBCd6V56yA==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:IsE3dr5AarufpKl+3w==,iv:GYZwqtR2ENDFKroerfv9tRAKdYD7+ln9Z01C7MB5nE4=,tag:Z5v0fLyCuGDKRykSHxyOMA==,type:str]
    PRIVATE_DNS_IP: ENC[AES256_GCM,data:BEwYCkY8tVMkGMKkDVD6qiE0Iw==,iv:zmDCA7es/TjE7iyRGu3nVHioB8SIWkPtF8W9qtT9+Ls=,tag:JECnI4oBSoWMzvs/2Ij18w==,type:str]
    SECRET_VOLSYNC_RESTIC_PASSWORD: ENC[AES256_GCM,data:JXx2bB5SQ1tGwJ2FZNh8Mojc5ayeLHLXPBGumez3fM+DnQ==,iv:hXIo2FtlrhftGW04vGZbgFcwzSD6GXYe9E+7jpFYf7Q=,tag:gt1a1CLKlhO86bqqT/7Mlw==,type:str]
    SECRET_VOLSYNC_S3_ACCESS_KEY: ENC[AES256_GCM,data:l/1uE6BKmUlsn+dgHyPrAm0sV8Y=,iv:IMqTzr7LncUZGlaZvpZAVdQIeF/+R01KdcOg+i/ROnA=,tag:lT92Ow89vu7+eSMNYtSaKg==,type:str]
    AWS_SECRET_ACSECRET_VOLSYNC_S3_SECRET_KEYCESS_KEY: ENC[AES256_GCM,data:dDWYr7x+tISoZbN49Vc+bvdcAKsaWucP/NeI9JBJHkku6qNyx5OUMw==,iv:ITcivravFcM2M/H6QnUbYk1hgAu+FAsfqdxxdXuXYqU=,tag:kKwky2XGBeCNC8+TSAjM0Q==,type:str]
    S3_DOMAIN_EXTERNAL: ENC[AES256_GCM,data:6ViJlO75aXAlZaqS/l3WhlGUhSriPLsQ7NFgDuGovULW+UQqe1G07lIn,iv:wD9teHeVO5kNJCd2rsvRDXfeovdVZhvpcDXu7LzdeEE=,tag:6w/JVPbI7E33iYCVzLteag==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dlBwNUEwOVlDRFR6dTlK
            b3BOS01JalVya1FBOHVrT2xLT3RhVVFZd1hvCnhBdUIxNi9FTjkyV1JhTStRSVZB
            N1pwNXZYWkkyNE9pdlk2U25Ma2ZsTU0KLS0tIFFnamlRWmJUYUE4SnlycTE4VEZk
            OGg0djNiTFU1MDI1SUUxRzBjTXFpa3MKPHH5a1BRqj0nD0oKzJoQWKf98PvX5jpS
            WXrqsXdvgCo77LdXTKnT7THBwe8sDA97NVQiEWJ2gsd4qDbbfop28A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T21:18:28Z"
    mac: ENC[AES256_GCM,data:fdfsT/TV100inoRiG3jT6C9ewYgu8Du8Q0B/MEiWrxxCEKbIYOvKRjY87hFrb+KM0aGcGM2BL4pfxHetwITf6vTmbgPktHI2p31CkzJtZrleYb53DEt1xlaZxQuTzGfjLiqN02LT1DsFRWU+O/m4bCGEQxgE4vvlg69XyWcSB1U=,iv:aHFv7FU3hoGbj/VDLPYZhkpzWFkCocuZq/RnHU23bV0=,tag:ObY3gjEG/pJEe+wj+4YvQg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
