apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:XfdwVq4CqQEnuA==,iv:X3ny12B2UTA1pfGjBcZ0eZQeSclsSP6RNTDXU8YBlUk=,tag:xIiVtSObTSCWUSt0fYoOPg==,type:str]
    SECRET_WORK_DOMAIN: ENC[AES256_GCM,data:BZ5HSM3jwME=,iv:a0OVyYWrU1uCInF4XVi2g/xUF3S2luVtXnYGCaouN98=,tag:wbDHxRH2BWQFD6cuHl1OqQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:l6PD3x48RYMaw0dcAvc=,iv:6SASQwwNEpqYbHQQ9thr7EK13l7wx0Lz/yGkCct3hHo=,tag:wzB3LUN5Fbk2st2q04Xk6Q==,type:str]
    VPN_DOMIAN: ENC[AES256_GCM,data:ZfW//s+mNgI2ZXvZRMs=,iv:io3WpmdsYyrfLwfFkBt181hnC4DwZsucZJT6kigyHKg=,tag:+aZY/Sxx3rXDkBCd6V56yA==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:IsE3dr5AarufpKl+3w==,iv:GYZwqtR2ENDFKroerfv9tRAKdYD7+ln9Z01C7MB5nE4=,tag:Z5v0fLyCuGDKRykSHxyOMA==,type:str]
    PRIVATE_DNS_IP: ENC[AES256_GCM,data:BEwYCkY8tVMkGMKkDVD6qiE0Iw==,iv:zmDCA7es/TjE7iyRGu3nVHioB8SIWkPtF8W9qtT9+Ls=,tag:JECnI4oBSoWMzvs/2Ij18w==,type:str]
    SECRET_VOLSYNC_RESTIC_PASSWORD: ENC[AES256_GCM,data:JXx2bB5SQ1tGwJ2FZNh8Mojc5ayeLHLXPBGumez3fM+DnQ==,iv:hXIo2FtlrhftGW04vGZbgFcwzSD6GXYe9E+7jpFYf7Q=,tag:gt1a1CLKlhO86bqqT/7Mlw==,type:str]
    SECRET_VOLSYNC_S3_ACCESS_KEY: ENC[AES256_GCM,data:l/1uE6BKmUlsn+dgHyPrAm0sV8Y=,iv:IMqTzr7LncUZGlaZvpZAVdQIeF/+R01KdcOg+i/ROnA=,tag:lT92Ow89vu7+eSMNYtSaKg==,type:str]
    SECRET_VOLSYNC_S3_SECRET_KEY: ENC[AES256_GCM,data:SBSspIQXvvRCZtjvSOGSWFZVdUO9ai/QKLSaKeg4FmW9eb49vhgpzg==,iv:TS24ifWJw9svETyYB6BhdIi3HZbJusdiy97hfkt3EG0=,tag:8jSjB21eOEpE+7eu1hqlcw==,type:str]
    S3_DOMAIN_EXTERNAL: ENC[AES256_GCM,data:ZP37+/98AYsbArEUPQ4X1VdkP50Xz/R6vdf8xWEkaAMGcCH9x9cq,iv:pq0ScCdW6+ujOs3Wj5i0UpUg4jUgdGJTf0/QkwKo6Kg=,tag:avo5sJ+6eSazzkxhEcNgGg==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dlBwNUEwOVlDRFR6dTlK
            b3BOS01JalVya1FBOHVrT2xLT3RhVVFZd1hvCnhBdUIxNi9FTjkyV1JhTStRSVZB
            N1pwNXZYWkkyNE9pdlk2U25Ma2ZsTU0KLS0tIFFnamlRWmJUYUE4SnlycTE4VEZk
            OGg0djNiTFU1MDI1SUUxRzBjTXFpa3MKPHH5a1BRqj0nD0oKzJoQWKf98PvX5jpS
            WXrqsXdvgCo77LdXTKnT7THBwe8sDA97NVQiEWJ2gsd4qDbbfop28A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T21:32:14Z"
    mac: ENC[AES256_GCM,data:VW//VfRHKn7+oOKJsHmAOo/GjyIvqlUUZi8cMfOkEJUTKNFLNOuUW4ynQhTxmqDSSiUE1mlEfqArMxiF5SK76ETFoUnQWiBidTLmYLjSJo6X5xAwVPkA0h/odTLDNae5E41oXA0Lwtqv9wbp8K0vLg4VuhXPziD2grti7xocnFo=,iv:VYFSy3BE62/SpbGAoP8dvOfa2j1hvgepywJDcVKXrhg=,tag:gqxMqwzhszGgKeX9QcueVA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
