apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:XfdwVq4CqQEnuA==,iv:X3ny12B2UTA1pfGjBcZ0eZQeSclsSP6RNTDXU8YBlUk=,tag:xIiVtSObTSCWUSt0fYoOPg==,type:str]
    SECRET_WORK_DOMAIN: ENC[AES256_GCM,data:BZ5HSM3jwME=,iv:a0OVyYWrU1uCInF4XVi2g/xUF3S2luVtXnYGCaouN98=,tag:wbDHxRH2BWQFD6cuHl1OqQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:l6PD3x48RYMaw0dcAvc=,iv:6SASQwwNEpqYbHQQ9thr7EK13l7wx0Lz/yGkCct3hHo=,tag:wzB3LUN5Fbk2st2q04Xk6Q==,type:str]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:Y99u7bWLPsyjNIsYjMnBbg==,iv:PlgxtmTz/mKdtCUXv9EsSwcOV5eoawoBSuZ7qM7tiJI=,tag:d9el9Iq4ZugsuCzh7zLq1A==,type:str]
    VPN_DOMIAN: ENC[AES256_GCM,data:BqA+mqQ1fecgQU67onM=,iv:g1CD90BXKA5iAnfbcl1Ydm6/b2b0lGL8AEvf8MEK7hQ=,tag:q0yWTqguA6ENdSdpOBp+xA==,type:str]
    EXT_CLUSTER_DOMAIN: ENC[AES256_GCM,data:imND/cJwlO4EznfYSoEBPw==,iv:AHguFGDIbSguwaLoGjfZ554i48z5tjIaGIYHULPlsH8=,tag:Cgz8uzgrL/VcXz49YnQUOQ==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:IsE3dr5AarufpKl+3w==,iv:GYZwqtR2ENDFKroerfv9tRAKdYD7+ln9Z01C7MB5nE4=,tag:Z5v0fLyCuGDKRykSHxyOMA==,type:str]
    PRIVATE_DNS_IP: ENC[AES256_GCM,data:BEwYCkY8tVMkGMKkDVD6qiE0Iw==,iv:zmDCA7es/TjE7iyRGu3nVHioB8SIWkPtF8W9qtT9+Ls=,tag:JECnI4oBSoWMzvs/2Ij18w==,type:str]
    SECRET_VOLSYNC_RESTIC_PASSWORD: ENC[AES256_GCM,data:JXx2bB5SQ1tGwJ2FZNh8Mojc5ayeLHLXPBGumez3fM+DnQ==,iv:hXIo2FtlrhftGW04vGZbgFcwzSD6GXYe9E+7jpFYf7Q=,tag:gt1a1CLKlhO86bqqT/7Mlw==,type:str]
    SECRET_VOLSYNC_S3_ACCESS_KEY: ENC[AES256_GCM,data:l/1uE6BKmUlsn+dgHyPrAm0sV8Y=,iv:IMqTzr7LncUZGlaZvpZAVdQIeF/+R01KdcOg+i/ROnA=,tag:lT92Ow89vu7+eSMNYtSaKg==,type:str]
    SECRET_VOLSYNC_S3_SECRET_KEY: ENC[AES256_GCM,data:SBSspIQXvvRCZtjvSOGSWFZVdUO9ai/QKLSaKeg4FmW9eb49vhgpzg==,iv:TS24ifWJw9svETyYB6BhdIi3HZbJusdiy97hfkt3EG0=,tag:8jSjB21eOEpE+7eu1hqlcw==,type:str]
    S3_DOMAIN_EXTERNAL: ENC[AES256_GCM,data:ZP37+/98AYsbArEUPQ4X1VdkP50Xz/R6vdf8xWEkaAMGcCH9x9cq,iv:pq0ScCdW6+ujOs3Wj5i0UpUg4jUgdGJTf0/QkwKo6Kg=,tag:avo5sJ+6eSazzkxhEcNgGg==,type:str]
    SECRET_MEDIA_SERVER: ENC[AES256_GCM,data:C2/kydn78vJT5Sl27Vg=,iv:4KuACQBcbT7sQ3Wgj7nylNG2Qx+4McqiYXU/mJ99hs0=,tag:L4YI3Orh5NLMyNDPuSHTJg==,type:str]
    SECRET_SMTP_SENDER: ENC[AES256_GCM,data:dTMEd7A8mc2UZBs2bT2ttVRq7Qri,iv:sFdIycG/C45/AOh0+E1+ejzrCQdcB1423WYda2bpJZE=,tag:OfNjFuctoFVKlEsLtWvW1A==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dlBwNUEwOVlDRFR6dTlK
            b3BOS01JalVya1FBOHVrT2xLT3RhVVFZd1hvCnhBdUIxNi9FTjkyV1JhTStRSVZB
            N1pwNXZYWkkyNE9pdlk2U25Ma2ZsTU0KLS0tIFFnamlRWmJUYUE4SnlycTE4VEZk
            OGg0djNiTFU1MDI1SUUxRzBjTXFpa3MKPHH5a1BRqj0nD0oKzJoQWKf98PvX5jpS
            WXrqsXdvgCo77LdXTKnT7THBwe8sDA97NVQiEWJ2gsd4qDbbfop28A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T15:52:48Z"
    mac: ENC[AES256_GCM,data:bopAo8s8wkkh9VuoAZg2HF4eJ/cUm+zrfIxdDzYVt7xcAT6llxriev+LV4xnXbcu6L96XL+lOneDc1wrv/g9fRnZ3/yp3GUcAZN0pCb06vwRdYQbPddS1EqEVNFJ24oAE2FRbaPfrgjlwXwSo+5b5uhkE6pu4MTk7e8gBG0uozE=,iv:imOJgYVoKQaPS6WNAS4+fbmrulnXxn3fAQ88Hs1unAY=,tag:HlemAfCxAzhPx0p2k978nA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
