apiVersion: v1
kind: Secret
metadata:
    name: volsync-kopia-secret
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:4mv8Nacai1eybbbxXKvmidknmHo=,iv:krenUdHssChTKpaf5nfDlcL96eg/4uCdZ1qjS6zp4t4=,tag:W8g0K4J3ZsTlHXajoQM2SA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DB2isx4EXE/vcQt5MnLq6Skx+eLUoNsynBKWuNEWj5wU8pHqZDzjfQ==,iv:944ifbaYZKwlMjOQSMu7qLJp7JwELQ0VnyJSi4q1kI8=,tag:/SBcR3cLl6CzddvML9HrPg==,type:str]
    AWS_S3_BUCKET: ENC[AES256_GCM,data:Z3NYloLl/4TXqw==,iv:4Lz5UKGhcnoWJjhwjPI3/8AgHm6Oq6+HZxkwJO7L/Hg=,tag:c6+Sx5vaOl61MZgVhl/Nxg==,type:str]
    AWS_S3_ENDPOINT: ENC[AES256_GCM,data:UiD9pdXr7TVJNSOfquTV4Lm5cZNvFLkGlsTv,iv:7mS1Y1VKkUffT/ydMhhRc98pjO0dhf6iJDAG/VgDulg=,tag:QfaTKQXbftHpxY+fgEnvfA==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:wjKndowETZaw8Q==,iv:42f2svS6VNExqd9XwFNlln8OTs74OAtrWnWmwnz8Iuc=,tag:z/rKVDzXNiwbEGHd5iAtxw==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:1vd+/lvgzVfDBi4QoO1Xdw==,iv:Cnr7wFKXPKAYpM0C5ePtaWmZ+DDHFvKcroWmCm0hR50=,tag:KF5f1VAI1LlmS6G0JXtUoA==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:JkmKUGWgFrDl8lPg0f4DT7uBmmwVRx7wxbju0Gd1cicowCr106kjkMgKSUAHnejHTzwMyfQ52ORwaOhAe+vi1w==,iv:yrH86DXHvEjRQfGAFFLTZDPazfrwX4GIX1N6iExNBFE=,tag:9qR+bQ/8yCEkzDiXXibqjg==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dlBwNUEwOVlDRFR6dTlK
            b3BOS01JalVya1FBOHVrT2xLT3RhVVFZd1hvCnhBdUIxNi9FTjkyV1JhTStRSVZB
            N1pwNXZYWkkyNE9pdlk2U25Ma2ZsTU0KLS0tIFFnamlRWmJUYUE4SnlycTE4VEZk
            OGg0djNiTFU1MDI1SUUxRzBjTXFpa3MKPHH5a1BRqj0nD0oKzJoQWKf98PvX5jpS
            WXrqsXdvgCo77LdXTKnT7THBwe8sDA97NVQiEWJ2gsd4qDbbfop28A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T11:39:43Z"
    mac: ENC[AES256_GCM,data:chSQ1O+dI6/WmbontSm8up+nj/n9tIw4n9igIyhZMuTiI3NRMuJbamMUBXjwecZDEW9NrKeulZNn4dcyQmwrMJ8OyG9q+JG5C1XLyLCMqmRH+0UdaMeull/dY07uMCOOjR+UpV/38ETE05K1J/aLLpvkl88vkoTsqrlVEfYte98=,iv:dsQKQnm950V6iqp2bpAoVArH0YeDtvjnbRdMv52+YvQ=,tag:mEzJWK1kHok7iwN3uOx2Kg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
