---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud-collabora
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: collabora
  values:
    controllers:
      collabora:
        containers:
          app:
            image:
              repository: collabora/code
              tag: 26.04.2.1.1
            resources:
              requests:
                cpu: 150m
                memory: 768Mi
              limits:
                memory: 3Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
            env:
              extra_params: --o:ssl.termination=true --o:ssl.enable=false --o:security.capabilities=false --o:logging.level=error
              aliasgroup1: https://files.albdev.cloud:443
              domain: files\\.albdev\\.cloud

    service:
      app:
        ports:
          http:
            port: 9980
            
    route:
      app:
        hostnames:
          - collabora.albdev.cloud
        parentRefs:
          - name: envoy-external
            namespace: network