---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: seerr
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: ${VOLSYNC_UID}
        runAsGroup: ${VOLSYNC_GID}
        fsGroup: ${VOLSYNC_GID}
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      seerr:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/seerr-team/seerr
              tag: develop@sha256:d3c65d5bc1e45e10ada5203487f53318c5cbab177d854b0cffcf298839423a12
            env:
              TZ: ${TIMEZONE}
              LOG_LEVEL: "info"
              PORT: &port 80
#            envFrom:
#              - secretRef:
#                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/status
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames: ["{{ .Release.Name }}.${CLUSTER_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
      vpn:
        hostnames: ["{{ .Release.Name }}.${EXT_CLUSTER_DOMAIN}"]
        parentRefs:
          - name: envoy-vpn
            namespace: network
            sectionName: https

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/config
      tmp:
        type: emptyDir