---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: ${VOLSYNC_CAPACITY}
  storageClassName: local-hostpath