apiVersion: v1
kind: Secret
metadata:
    name: envoy-oidc-secret
stringData:
    client-id: ENC[AES256_GCM,data:6ehTtPn0cS+02wJpGPVr1blH+MceGJjDPnG5Eom+Y1kC34pC,iv:Ejhvz51goVcpo5xD8Xu2zk6Zv7vjdeRphsdRtQAdWRg=,tag:CFEBx/jPq28sqp6WUBVXVQ==,type:str]
    client-secret: ENC[AES256_GCM,data:s6/FV/ywkZ1wH5/GYq6uJMcXpGtif3kjppkbHnbi2mo=,iv:ex/UNA9dvXZ0ewI3/jCmOdLSg7M0tbTXTiyZCwKDOuE=,tag:XozDd2OattL+lBm6U/3BFA==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNTB1MnNaUnZjOXdoUE9D
            NElQS2d4M3F2cFRDbW1Da0dhMXBRMXMyckJFCkF4N0lGNEM2QWtvSVJGM3NsdllN
            V0srNVVzTlhML1ZXRmI2bmw5WnRqUWsKLS0tIFRLTC8yQm1lQmxIdXo1SXFMYnRs
            aWpQakt4VTlzb2Nka0tiUDZiOXUwMTQKFdZiptbnZvXJVvwSy87WHXz1wuKkiOIX
            1ZDyA8bVI93p+/Y/NIrItdN4JuvNVMiBCLzYjMB29x4wirTmCqDNBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T12:59:08Z"
    mac: ENC[AES256_GCM,data:dTP4z39BUOFEVkSxgHGjY/v6sVEDRFBdUKJ5YOpnS+rBqRmhCyb8zaJbbWOWUfETx2g04Kl4MWSgTWSubqowDqkqMP10oDx2OP3vtHfjz+cz8wYIkiOSZYpnJ3vKjvbQbTrUvVT2PFYhZ+tNIg6ieDP/oDxrUz9fxBRzT6lfMUY=,iv:HRZIOhFT64P6JymWo+N9g5/qN+ClDteFGvjyRLc6PCU=,tag:lT2rq08vUHRc2gaoYa72XA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
