apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:ZRVtiPQ0fCJPtg==,iv:c73DGOReRhE/ns5iQptf2tm7ihiGxdMpUqiRmiWIk/4=,tag:DMHXnw+OiHZeptS4Y/Tlkw==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:aK6200tiD7+LeZ2t5cFbIqkk++TQmjG3eAM3w6x4HblhN45iGTU4alI=,iv:rmR3+Y8dCIFU9kssuZlHUsDmw/Ys1aIeHTZPFEMJWuo=,tag:wJhim9et5BweKmjgTm1AjA==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:WMtKM3qkONsON7My7wum,iv:u8eWK40EIofB5oqbP0aR1zabBdAjksiSmTcjRLXDm2c=,tag:t0l0R6gMcjjFj6VC9V+hAw==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:lgrQUwxdbmCEp5J+VEktsQStkM3w,iv:vezFPJ9vUr6z3rMPuGTUGHyx1PPkFs2Zt/A9l/MzbWE=,tag:/eN5eiAdd1tMyQk1NEShdA==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvKzdyU083MjkzM1gxeWlk
            cGZ5SFZPLyttM0RRL2pxYVY0S1RTckkwK0RzCkdWbkM3WUhEc3ZhYTl1MktvaUdU
            aGU5ZU5jcnNzSEhRbVh2NzRJQWRlYXcKLS0tIE1XbmRob1g3djFMckNucUxEUmky
            RTh1dlpEVTlkd0xkb1hhVkw5eFhHc1kKi4RnpW6+aS7oVo6Xsd85rh74ZnDi9y10
            8kSNhqU39uesK2FXe94RndNmbjUBpzW6fGxkXtG58/nACF+mUcnIrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-08T20:46:01Z"
    mac: ENC[AES256_GCM,data:K6r+GT2bztmotGJb7DR5DXRBOvm8GRGtJYTNBqGQ15b95bQS0u3QOAcLGwmUUJvjOCXMIAymLEt5hgLllCf49aVyNQuKkVsjKotvXZdh/CmQKJ5+o8KbQivYcBU2P2JJs+YOMpn0PDSjK8ABjbm0vdD2YWS/kFavJw9O3pRJI1c=,iv:g8zOhMvXr+KvX+MJZ0b/T3mA987X1aIynpg3SYwlrH8=,tag:MYRIr2s+kvc6CHHKyx6Sxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
