apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:ZRVtiPQ0fCJPtg==,iv:c73DGOReRhE/ns5iQptf2tm7ihiGxdMpUqiRmiWIk/4=,tag:DMHXnw+OiHZeptS4Y/Tlkw==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:aK6200tiD7+LeZ2t5cFbIqkk++TQmjG3eAM3w6x4HblhN45iGTU4alI=,iv:rmR3+Y8dCIFU9kssuZlHUsDmw/Ys1aIeHTZPFEMJWuo=,tag:wJhim9et5BweKmjgTm1AjA==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:gtV7vyRuyunNCcOSrA==,iv:9JpNjCUS/v4XjMQOErR19NaAhmu1xhJ9uCLg/Z2UJfk=,tag:RU9yx4vAgkP+jsg7uJBfNA==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:lgrQUwxdbmCEp5J+VEktsQStkM3w,iv:vezFPJ9vUr6z3rMPuGTUGHyx1PPkFs2Zt/A9l/MzbWE=,tag:/eN5eiAdd1tMyQk1NEShdA==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvKzdyU083MjkzM1gxeWlk
            cGZ5SFZPLyttM0RRL2pxYVY0S1RTckkwK0RzCkdWbkM3WUhEc3ZhYTl1MktvaUdU
            aGU5ZU5jcnNzSEhRbVh2NzRJQWRlYXcKLS0tIE1XbmRob1g3djFMckNucUxEUmky
            RTh1dlpEVTlkd0xkb1hhVkw5eFhHc1kKi4RnpW6+aS7oVo6Xsd85rh74ZnDi9y10
            8kSNhqU39uesK2FXe94RndNmbjUBpzW6fGxkXtG58/nACF+mUcnIrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T20:11:46Z"
    mac: ENC[AES256_GCM,data:RKPucOUcamjZIQ35Cg4CclrX96PB1dbw3j8gk7/O2+qp8KTfNBo2c5oBIPMAYDuNgS2JgIgVvJSmW/4oc6Tph9dvsp0IBeFbY0AYskDDRQX3yT/cE5JthWt8vmiugDLsN7NddP+D2LDmRrQSf/lEBuVYeWPDQSoaILmkyo8qdnw=,iv:TFkH42xLzAMmuUIYKZYPMsKkwyBBtGVLJgxifGO33x4=,tag:G54767mgi5PjlloySI0QiA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
