apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: externaldns-netcup
spec:
  chartRef:
    kind: OCIRepository
    name: externaldns-netcup
  interval: 1m
  values:
    fullnameOverride: externaldns-netcup
    logLevel: info
    domainFilters:
      - albdev.cloud    
    policy: sync
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/mrueg/external-dns-netcup-webhook
          tag: 0.4.0
          pullPolicy: IfNotPresent
        securityContext:
              runAsNonRoot: true
              runAsUser: 65534 
              runAsGroup: 65534
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
              seccompProfile:
                type: RuntimeDefault
        env:
          - name: NETCUP_CUSTOMER_ID
            valueFrom:
              secretKeyRef:
                name: externaldns-netcup-secret
                key: NETCUP_CUSTOMER_ID
          - name: NETCUP_API_KEY
            valueFrom:
              secretKeyRef:
                name: externaldns-netcup-secret
                key: NETCUP_API_KEY
          - name: NETCUP_API_PASSWORD
            valueFrom:
              secretKeyRef:
                name: externaldns-netcup-secret
                key: NETCUP_API_PASSWORD
        extraArgs:
          - --netcup-customer-id=$(NETCUP_CUSTOMER_ID)
          - --domain-filter=albdev.cloud
          - --log-level=info
    extraArgs:
          - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
          - --crd-source-kind=DNSEndpoint
          - --gateway-name=envoy-external 
    podAnnotations:
          secret.reloader.stakater.com/reload: externaldns-netcup-secret
    resources:
      requests:
        cpu: 13m
        memory: 42M
      limits:
        memory: 42M
    serviceMonitor:
      enabled: true
    sources:
      - crd
      - gateway-httproute
    triggerLoopOnEvent: true
    txtOwnerId: main
    txtPrefix: "k8s."