apiVersion: v1
kind: Secret
metadata:
    name: externaldns-netcup-secret
    namespace: network
stringData:
    NETCUP_CUSTOMER_ID: ENC[AES256_GCM,data:7kIK99AV,iv:sbeE8eNZLwnCpQIRNuCM1jyrN5lOD7zTxbO2qo3oeSc=,tag:qF4ocpjGh3Ll14+jMlwI8g==,type:str]
    NETCUP_API_KEY: ENC[AES256_GCM,data:duVTIiurFe58A7ReDZZslKxvLjz374UqiN3Er8sAqwqxgJfFN8YLGKpuz9A9ms7xyAM=,iv:DQMbN/ZtYJWJeRilueQAZlgzFiuRXqYubQOhbB+VW5U=,tag:EC7RNDplkSZ3SExpVo6lFg==,type:str]
    NETCUP_API_PASSWORD: ENC[AES256_GCM,data:8ENKqIunrCH1OwV3sZFYR0QI/vcFu2aA06vEgKCEFOdmeZbA8x1d2bsLtGtgxlV5S/8=,iv:kCnS3i1I6vM9evJotlCr6BW/pWqxRABwWq3cPZj+RGU=,tag:y6QJFtRmOzBTX9syCU6Oaw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNTB1MnNaUnZjOXdoUE9D
            NElQS2d4M3F2cFRDbW1Da0dhMXBRMXMyckJFCkF4N0lGNEM2QWtvSVJGM3NsdllN
            V0srNVVzTlhML1ZXRmI2bmw5WnRqUWsKLS0tIFRLTC8yQm1lQmxIdXo1SXFMYnRs
            aWpQakt4VTlzb2Nka0tiUDZiOXUwMTQKFdZiptbnZvXJVvwSy87WHXz1wuKkiOIX
            1ZDyA8bVI93p+/Y/NIrItdN4JuvNVMiBCLzYjMB29x4wirTmCqDNBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-21T21:44:08Z"
    mac: ENC[AES256_GCM,data:9DNHa8+qMoOqx7QZUeJqkKwMLpaj6F1NOho6MUXi9KWb6SGXbLd9y5dFWhOoxjqxrsWeBVbELha8WFEHVg/hT+URwvfTjt5XlinesAQExOyncgJSjPfR9SZ8jEihi4guV85q+u2fB4JqZdcf90J6PzIvlqRPQP/4g69RPtuUKp8=,iv:i1Yhc28RWnFo7AOMSAlgm9GXq1yOmsiMWkC+hsmDJ2w=,tag:oHkzwGS2gBWFpnc89HKPBQ==,type:str]
    version: 3.13.0
