apiVersion: v1
kind: Secret
metadata:
    name: mealie
    namespace: selfhosted
stringData:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:AFyJHsgQLV1JCslHCiAsLYbpMAoouKMtkPYIDELkWeM=,iv:adbv7HEPgjTb+SEDgQppVwLNrg9RwryEcSljKQC9wYM=,tag:FOXgIbQBANbO2ZQ+roZ1FQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:UmlMdWBWseiD9CxULMaB9NDK449nBcXnjBK4io1hC1dg5jrK,iv:awLsCXgnxybNu6bXAVRelAre+1AZVyX9mwkY+qTZw2c=,tag:+DAJL4SU9qpdiUcplMAmDg==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGhnZDdjR1VkYWhrRXJx
            SmRtV1plWUNmL2ZlMTNwbGErRVB4SDRLcUI4CkFMQ0NEVStvUUVMR2hnSTdCUHha
            ek1JcEN6U3lDWkFjSCtIem1JdEltYzgKLS0tIHZtYWVweXdsR0hxSmswQ0hnUTRz
            VDNKWlowS1VXZURES0dJMzRQaWRhQ3cKQFvSLEyCn3WbsD+wCbM4OwuSkHrAr3i1
            fYsM2EhWu/knKGh/zYYqzKpDyV+tjPmvjvI8wWpkZ4RFGTVL8WT/rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T14:14:44Z"
    mac: ENC[AES256_GCM,data:QyvaMKoBYyzAu4096S/OyjHvdmJDK6OkKu5G9VZIrl1A+V0spgkDdTnNUvfNDd5lMxwkNBNTSrLXWe+hp0hZZBVvLsYJcB7ItaMXC2Km0Yit59vtvQ+lwaciSakp0SOasYhksZunTIdj8QerzI5tbjnWgxbt+wWl7ffJwXWRf0Q=,iv:XpN7WJB9+PgeaUGObkaS/wX/V7kwPV1Owz0bwRGstUU=,tag:k7+LzzHMXys2k1Y0qgnOag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
