---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: paperless
  values:
    controllers:
      paperless:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.20.8
            env:
              PAPERLESS_URL: "https://{{ .Release.Name }}.${CLUSTER_DOMAIN}"
              PAPERLESS_PORT: "8000"
              PAPERLESS_TIME_ZONE: "${TIMEZONE}"
              PAPERLESS_WEBSERVER_WORKERS: "2"
              PAPERLESS_TASK_WORKERS: "2"
              PAPERLESS_DATA_DIR: /usr/src/paperless/data
              PAPERLESS_MEDIA_ROOT: /usr/src/paperless/media
              PAPERLESS_CONSUMER_POLLING: "60"
              PAPERLESS_CONSUMER_RECURSIVE: "true"
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
              # Configure OCR
              PAPERLESS_OCR_LANGUAGES: deu
              PAPERLESS_OCR_LANGUAGE: deu
              # Configure redis integration
              PAPERLESS_REDIS: redis://paperless-redis.selfhosted.svc.cluster.local:6379
              # Configure user permissions
              # Configure admin user
              PAPERLESS_FILENAME_FORMAT: "{correspondent}/{created_year}/{correspondent}_{document_type}_{created}"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 2500Mi
      redis:
        replicas: 1
        strategy: RollingUpdate
        
        containers:
          redis:
            image:
              repository: ghcr.io/valkey-io/valkey
              tag: 9.0.2
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 128Mi

    service:
      app:
        forceRename: paperless
        primary: true
        controller: paperless
        ports:
          http:
            port: &port 8000
      redis:
        controller: redis
        ports:
          http:
            port: 6379

    persistence:
      data:
        existingClaim: ${VOLSYNC_CLAIM}
        advancedMounts:
          paperless:
            app:
              - path: /usr/src/paperless/data
                subPath: data
              - path: /usr/src/paperless/media
                subPath: media
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${CLUSTER_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port