---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headscale
spec:
  chartRef:
    kind: OCIRepository
    name: headscale
  interval: 1h

  values:
    controllers:
      headscale:
        type: statefulset
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/juanfont/headscale
              tag: v0.27.1
            command: [headscale, serve]
            envFrom:
                - secretRef:
                    name: headscale-secret
            securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
            probes:
              liveness:
                enabled: true
                type: HTTP
                path: /health
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 12m
                memory: 128M
              limits:
                memory: 512M

    service:
      app:
        ports:
          http:
            port: 8080
            
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          cert-manager.io/private-key-rotation-policy: Always
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-headscale-cors@kubernetescrd"
        hosts:
          - host: "headscale.onji.space"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: "headscale.albdev.cloud"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "headscale.onji.space"
              - "headscale.albdev.cloud"
            secretName: headscale-tls

    route:
      app:
        hostnames:
          - headscale.onji.space
          - headscale.albdev.cloud
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
          - matches:
              - path:
                  type: PathPrefix
                  value: /api
    persistence:
      data:
        existingClaim: headscale-local
        globalMounts:
          - path: /etc/headscale
            subPath: config
          - path: /var/lib/headscale
            subPath: data
      tmp:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /var/run/headscale
            subPath: run
            readOnly: false