---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headscale
spec:
  chartRef:
    kind: OCIRepository
    name: headscale
  interval: 15m

  values:
    controllers:
      headscale:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/juanfont/headscale
              tag: v0.27.1
            command: [headscale, serve]
            envFrom:
                - secretRef:
                    name: headscale-secret
            probes:
              liveness:
                enabled: true
                type: HTTP
                path: /health
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

            resources:
              requests:
                cpu: 12m
                memory: 128M
              limits:
                memory: 512M

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
    service:
      headscale:
        controller: headscale
        ports:
          http:
            primary: true
            port: 8080
            
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          cert-manager.io/private-key-rotation-policy: Always
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-headscale-cors@kubernetescrd"
        hosts:
          - host: "headscale.onji.space"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "headscale.onji.space"
            secretName: headscale-tls
    route:
      headscale:
        parentRefs:
          - name: envoy-external
            namespace: network
        hostnames:
          - headscale.onji.space
        rules:
          - backendRefs:
              - identifier: headscale
          - matches:
              - path:
                  type: PathPrefix
                  value: /api
            filters:
              - type: ExtensionRef
                extensionRef:
                  group: gateway.envoyproxy.io
                  kind: HTTPRouteFilter
                  name: headscale

    rawResources:
      respond-403:
        apiVersion: gateway.envoyproxy.io/v1alpha1
        kind: HTTPRouteFilter
        spec:
          spec:
            directResponse:
              contentType: text/plain
              statusCode: 403
              body:
                type: Inline
                inline: Access Denied

    persistence:
      data:
        existingClaim: headscale-local
        globalMounts:
          - path: /etc/headscale
            subPath: config
          - path: /var/lib/headscale
            subPath: data
      tmp:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /var/run/headscale
            subPath: run
            readOnly: false