---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: headlscale
  namespace: selfhosted
spec:
  hostnames: ["headlscale.${CLUSTER_DOMAIN}"]
  parentRefs:
    - name: envoy-external
      namespace: network
  rules:
    - backendRefs:
        - name: headscale
          namespace: selfhosted
          port: 8080
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Forwarded-For
                value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
              - name: X-Forwarded-Proto
                value: "https"
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: headlscale-upgrade
  namespace: selfhosted
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: headlscale
  http:
    upgrade:
      - type: tailscale-control-protocol