---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: headscale
  namespace: selfhosted
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
  hostnames:
    - "headscale.onji.space"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
          headers:
            - type: Exact
              name: Upgrade
              value: websocket
      backendRefs:
        - name: headscale
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: headscale
          port: 8080