apiVersion: v1
kind: Secret
metadata:
    name: headscale-secret
    namespace: selfhosted
stringData:
    HEADSCALE_SERVER_URL: ENC[AES256_GCM,data:u7iFcpSfOPMKpog8mA7758DG2yP4Kksz/F91kurccJ8=,iv:IChFA5DHEfsDgpby/g2njPp5x7V/7jeVEkJF99z6CM0=,tag:qEHR/qr3eVcEcMVMxzUCrw==,type:str]
    HEADSCALE_LISTEN_ADDR: ENC[AES256_GCM,data:/vjxll2zDFcnNHrs,iv:LjaBpmlctBAK07dgY8cp0pgfLExKhP1uS0voVOhWN1k=,tag:CyIPwGwp4DgeuqWo46PhmQ==,type:str]
    HEADSCALE_METRICS_LISTEN_ADDR: ENC[AES256_GCM,data:RvUQ3HGWijm7yJls,iv:83sTSEqjsF9VDXODXYnkmowQ/jvjmK7AIi7A5tbmkFo=,tag:pxK5rjca0vIFqy0L0rUUCQ==,type:str]
    HEADSCALE_NOISE: ENC[AES256_GCM,data:CYY=,iv:HE0Lvx+XIILYwE6boXPFdTdbvFtTf6sGELDr2cplUMQ=,tag:isQXrzBz3kUlJ0ZzobH+gg==,type:str]
    HEADSCALE_NOISE_PRIVATE_KEY_PATH: ENC[AES256_GCM,data:ZLTGD5/qeQGpAtG5i1c3W0BSp2JvpWum2dMIjsRHM6A=,iv:GeAQaAMHlYIcvmC4aAmPPoqnI7JWXONsnjftVwaSMQ8=,tag:ajs+8VZI9NdGCFJ9NmeYFg==,type:str]
    HEADSCALE_PREFIXES_V4: ENC[AES256_GCM,data:jBzF4rGKjFnwmdzBmQ==,iv:cHjH6EfVNi65B4/8XONA74Ss4hW7pGfMjxVlAhISUpU=,tag:Nv4zfwoQnYKBbbZsaMLs3w==,type:str]
    HEADSCALE_PREFIXES_V6: ENC[AES256_GCM,data:cjYAMKMF0mZXT+kTEdUy0pglgw==,iv:7FWi/IZRrrFhuR7lZyIOcPp4n2JlWDUBAgQ3rogN5r8=,tag:5ybzHSdgMSup6UoHY8H08Q==,type:str]
    HEADSCALE_POLICY_MODE: ENC[AES256_GCM,data:t+Bo+PmGl6I=,iv:fW6tlem2TdwoNxxCjHRHWyRxjZDy/RWs5W3lG+WwiJI=,tag:hHLsiABVeYGCyVhT0C//3g==,type:str]
    HEADSCALE_DERP_URLS: ENC[AES256_GCM,data:u435H9P7JU4tt+VhaUXC+6Mg3RuMhVIGn4rUmxAZ/fSqHILE8Mxig3xIVv32V3sk0KU=,iv:vcPErfFlqPTYTEyPdo32d2FjtB4z/Nw8ExcBZIcSp8E=,tag:NyM4MUCFyPwQMtqUBLsb7w==,type:str]
    HEADSCALE_DERP_AUTO_UPDATE_ENABLED: ENC[AES256_GCM,data:i7xOfg==,iv:KOr+rMo1MkZDszeuC7c7/w/juSBS6e9JJz54IQYs8Xo=,tag:zlt1FK7B1f5XhW/EmGDNVw==,type:str]
    HEADSCALE_DERP_UPDATE_FREQUENCY: ENC[AES256_GCM,data:p0XZ,iv:cX+Xs7avvVBS/1ixZlM/jgOcdrgF4UY7Ck8jjt0TFMk=,tag:pgrH9wVaveaN7wxcfeQDXQ==,type:str]
    HEADSCALE_EPHEMERAL_NODE_INACTIVITY_TIMEOUT: ENC[AES256_GCM,data:Dld8,iv:/o62Ay7r4bD/d7uqSfq4/7TZENj757CbYj5jeh0N/AY=,tag:9KRVnNJ8leDNvH1b7ikRIw==,type:str]
    HEADSCALE_DNS_NAMESERVERS_GLOBAL: ENC[AES256_GCM,data:d6BGkjHiUunH5g==,iv:Zxyh8/MduUlIiqNtchBh2hlIpJaEuuvYuqZgpTQfmrA=,tag:b4ov589QeYy4ofLLKK5Tlw==,type:str]
    HEADSCALE_DNS_MAGIC_DNS: ENC[AES256_GCM,data:GxMVEA==,iv:MF73TkUguuYuqwc4/cnyzQhap7vZbaYvpcYAloEyakM=,tag:4j4pLD42K1ppXS3tSmA0LQ==,type:str]
    HEADSCALE_DNS_BASE_DOMAIN: ENC[AES256_GCM,data:XdWOL72afpkCWZjNETc=,iv:4Ms5ElyO2OUQoPYP+cDuq356oCOd3+ERxomC4gVNVsc=,tag:owaER9U8MSS4N+7u/w6suA==,type:str]
    HEADSCALE_DATABASE_TYPE: ENC[AES256_GCM,data:TmJ3F4A+,iv:KHFVzUxMXHeT0LC/ieZWBUtS4BdNfEuXIKscScptg40=,tag:oMu40nbiY7yOajvUNCgIxA==,type:str]
    HEADSCALE_DATABASE_SQLITE_PATH: ENC[AES256_GCM,data:bqtaRkMAjE/UOxbV9F6x0nrV4SZp0oRCNnbm0A==,iv:6zMz7iAeOmaUd3W0hR38yREB6OJiRNJYP8C8fBv4SyU=,tag:0IglPeSn5tOxE4aravVipA==,type:str]
    HEADSCALE_PRIVATE_KEY_PATH: ENC[AES256_GCM,data:4DJQxhDF6qsfzZ1kZrNQhaWwJ6LvnK8CdjI=,iv:qKpH2p4bLYngzW58pQJPOyMAEKiEGWCkkWC4eSdkY2M=,tag:TGd6jvGZhYwNfHB8FFIMdg==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGhnZDdjR1VkYWhrRXJx
            SmRtV1plWUNmL2ZlMTNwbGErRVB4SDRLcUI4CkFMQ0NEVStvUUVMR2hnSTdCUHha
            ek1JcEN6U3lDWkFjSCtIem1JdEltYzgKLS0tIHZtYWVweXdsR0hxSmswQ0hnUTRz
            VDNKWlowS1VXZURES0dJMzRQaWRhQ3cKQFvSLEyCn3WbsD+wCbM4OwuSkHrAr3i1
            fYsM2EhWu/knKGh/zYYqzKpDyV+tjPmvjvI8wWpkZ4RFGTVL8WT/rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T14:50:29Z"
    mac: ENC[AES256_GCM,data:IF+sN5hccSP1eYqsRjRyvuo1d0efWwpTMtWf8yhMYeqPpKSqXCDloQ6V8tJpKZbVzCaSY+AU13+A9weL2Y51q4r7MdfCjBNP7CTC8fslzwu8VDbUEnx+Wh0z/dDiet4ksqwUJT46XY5xnq/IfkXbev9y1bVTZIAaBEt1KgzbExw=,iv:Nzyrkafn4klSGfSBR7Rqc9bUizm8lOYR1SREopNsthY=,tag:pQFRME6iid3amEIFc7K03A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
