apiVersion: v1
kind: Secret
metadata:
    name: ntfy-secret
    namespace: selfhosted
stringData:
    #ENC[AES256_GCM,data:wYdefhK1w0EuxhDpyNobb8A6XJDhM1b5A8rzLpqU8Sf0OROYEc1QBPUQWg/cECz1zDM=,iv:YvaTX6ThkZd1PHqN1s/10JyiNGrgEaEN+1KRs+NBX9c=,tag:nxfoCVfs7pL5Uy/at+v1CQ==,type:comment]
    auth-users: ENC[AES256_GCM,data:dblUhdqwrp1AZ1mEODh1JVXWYw4Mrp9spqYpeAdp0+ark5mxSkWi79O9UhzoKkQUiBmU8jmzO9F20CLnZlGJfzYL/ADpVo32QUwYHE+kbeK9liOSEhintgILMoWQfTi+A7zJWMvov2np6pZggls9G6aD3NKTuSoOnoWxgKVEnovpLRnBr6qMH8zLChQRQ1zfl6uFHOPKMItM82JE2zhJWUjUWghE829/se92U02FtmeUyvWQIgClCv08bEwk7strcSZ7ZbgfGkttLxCNFP9v1D8ZSZjlML8j+FA1mslQTDxfunE=,iv:PAw+I1kBwDY5lP1bmpsFv3amC5Jgf8chbhbpx56UIdQ=,tag:lRj29Mh7xjlqCcLPqYA7AA==,type:str]
    #ENC[AES256_GCM,data:c92lSWpiPmiKg8HEzSXakAgwbAFO7F579yM33LzMKMVBnRnv6X6P4vBY2+MSjj3oz/OPgM3c+1o=,iv:r5ilXXMHWPiDdyVMdF09legZ85Vmol2STNiphpk71Uo=,tag:hAiUemEoVBQvofexPCQrrA==,type:comment]
    auth-access: ENC[AES256_GCM,data:HeYGw/1exhL1Qt5mGv2fIdhPMLBhLWj/8/+QpyXJEVWtX+ITz0lIecsGT34=,iv:ZJUx7RxUpkP1HY+Oqawy6JiwRDG3PyJ2gtw4EYA9xUQ=,tag:3kIlvC9bvl/C9kn0vSkc9Q==,type:str]
    #ENC[AES256_GCM,data:FsbZ+A/CgwqRuI3SHS+vByqGo75348HniQEBHg==,iv:IV8jvi0820wonVAWfwg9hTcOODoDhOkhWpc/t7gTYwI=,tag:omD2ePWaOgdTpLcneBpGdA==,type:comment]
    #ENC[AES256_GCM,data:zImJRWPUtccQDQgvmdcqcRYdA4Thn34D/SFrTR+l3MU3QCYI+ve1h7L+/LXeoMLSO1vw/gRapGop+E5RPcGf5V6EgaI8ErQI8q+zx7umEkL25CA171k3VB4uXEAbQaOF8v8wMbAU/fQtKamsFw==,iv:4Ws3L/6gl433qv8R20yde/iqvRrLJ4hnDny1Ek9GhZ4=,tag:/5m61bqTXseIXZP4N/gaYA==,type:comment]
    web-push-public-key: ENC[AES256_GCM,data:sZBa7r6j/WqR/ZLdnucAb/rwTHSouu0vyEoGSX6IkVhQDIyABtRYO3VW7n5WUWaEus0uH7zAEKNL7DbqH1Q2yxxefRYMs4MqiWeROWri9wB2R6BjFT9M,iv:PJDgts9aTYjychJEoYDCPGVwuP7YfX74nDLcHvz1C+M=,tag:iwHDuri9weXGfdwe2V/vDA==,type:str]
    web-push-private-key: ENC[AES256_GCM,data:/ImahM1P1W0WEyMGaqQCmAkVGLE9Tq7NE+Y9hJpBkvWEB1aKx9sVODtvNw==,iv:VQdTSZ/sHzc5ZdLv02piUuswR+ki0UB9t5C7gyTT+2U=,tag:vPkp1uefLr2lQ1ztBwl5ow==,type:str]
    web-push-email-address: ENC[AES256_GCM,data:igbnxfW5Z+oW5TM+nUy+,iv:7IVowvsZVwzVUD1Il34s8K4xmWQqLAHcvN9MKayV0tM=,tag:0T/0xp6M21UCZlY1PjP3mQ==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGhnZDdjR1VkYWhrRXJx
            SmRtV1plWUNmL2ZlMTNwbGErRVB4SDRLcUI4CkFMQ0NEVStvUUVMR2hnSTdCUHha
            ek1JcEN6U3lDWkFjSCtIem1JdEltYzgKLS0tIHZtYWVweXdsR0hxSmswQ0hnUTRz
            VDNKWlowS1VXZURES0dJMzRQaWRhQ3cKQFvSLEyCn3WbsD+wCbM4OwuSkHrAr3i1
            fYsM2EhWu/knKGh/zYYqzKpDyV+tjPmvjvI8wWpkZ4RFGTVL8WT/rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T14:31:03Z"
    mac: ENC[AES256_GCM,data:WWWmHslodofiE2YFIS22loxysv0+iEU1aNxorOS2k/SWfiOXKtQiHxchgdolnEVy7HTEadBv/3N2jqx7tp6YyBDIijI2/PAvWUl/3QOKn+i9TDaVqD9lyFl3Ggg4JIJVr6vNnh8ouOmVuR5kR1yl8XTM+dZ2YRp1NCUGZxH/nEs=,iv:LnNxur/ZzV34DTeJ63VG+MY8cAN+GHf8j6mCnfl305k=,tag:ooqXi6Z2Htas8pRQa7M6vg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
