apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:XfdwVq4CqQEnuA==,iv:X3ny12B2UTA1pfGjBcZ0eZQeSclsSP6RNTDXU8YBlUk=,tag:xIiVtSObTSCWUSt0fYoOPg==,type:str]
    SECRET_WORK_DOMAIN: ENC[AES256_GCM,data:BZ5HSM3jwME=,iv:a0OVyYWrU1uCInF4XVi2g/xUF3S2luVtXnYGCaouN98=,tag:wbDHxRH2BWQFD6cuHl1OqQ==,type:str]
    AUTHENTIK_KEY: ENC[AES256_GCM,data:RXK03ovgH812ivldXa6F8nu/HqjX5chpgMDK3uHekUdrM8ab/Wp7Lp0Vdx5dFBy1tvBjrzlvjfjdrFSPsj49c77uM4yRedxVXRQKktHaQpE=,iv:zcHe6Ghe7DtME4XQD+7On4TDTvjNYUuZ+HG/ZpjWyAk=,tag:F9MWFNocLyy2yzmdv9v55Q==,type:str]
    AUTHENTIK_DB_PASS: ENC[AES256_GCM,data:VFxxkcpFZgi/w9kNa8+MeZBxoW7rqc75b0c62f/xaWMNPP954BXYL3bDapW9VERb4Q==,iv:VLynttpVQQngDFpmOGi8PsVATn01X5Xaxk2Z6Fa+mHQ=,tag:iI3Mb1a1wLlA2yd1Jva7Aw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:7lV3Wr730BhyKA==,iv:Opbyjq8QVNUHp+8U4yft5BOa61AHBCMPwGr3M+6/Tks=,tag:+Pe2r4QPUa7UjyW7yUg6JA==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dlBwNUEwOVlDRFR6dTlK
            b3BOS01JalVya1FBOHVrT2xLT3RhVVFZd1hvCnhBdUIxNi9FTjkyV1JhTStRSVZB
            N1pwNXZYWkkyNE9pdlk2U25Ma2ZsTU0KLS0tIFFnamlRWmJUYUE4SnlycTE4VEZk
            OGg0djNiTFU1MDI1SUUxRzBjTXFpa3MKPHH5a1BRqj0nD0oKzJoQWKf98PvX5jpS
            WXrqsXdvgCo77LdXTKnT7THBwe8sDA97NVQiEWJ2gsd4qDbbfop28A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T23:29:41Z"
    mac: ENC[AES256_GCM,data:uUrQHpaUp2eHBq1KaLguRt5awTveTlHyQyd1eGyLqZLEw2u5TtC9QT0CVCrSWDGhlZVHxDtIaTQPygOXuJ0THZtYgaP9Suj8wNZmvfFbmkmc6sCFdpzynWEsz2wz3qlmxajrS6IooKWGYHYcd5CVx6uX2zJ2Sl+W23xMXt+bGNs=,iv:H/OJNZzjifRe6EgSmQgnEcvj1mBCDT5jop9k596bX5k=,tag:0L1h0TpYYUjtToi2cvpGRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
