apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:1VgxWQ4xD7/orAmr,iv:HW7wm6QWsvTpNONC3bgDIXwi0BR5SKLxWQ0hpk6D7Yw=,tag:Erfbvg1Pwv4EGB4X3wPCPg==,type:str]
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:UTaoI3bfS4jYpaTU,iv:87uuBIM7oQaOgY1UUCY3jyACuAJ5j2YCkVrAZ6Cfv6c=,tag:OvzrBbmUe33yQxywV0XkLw==,type:str]
    AUTHENTIK_KEY: ENC[AES256_GCM,data:RXK03ovgH812ivldXa6F8nu/HqjX5chpgMDK3uHekUdrM8ab/Wp7Lp0Vdx5dFBy1tvBjrzlvjfjdrFSPsj49c77uM4yRedxVXRQKktHaQpE=,iv:zcHe6Ghe7DtME4XQD+7On4TDTvjNYUuZ+HG/ZpjWyAk=,tag:F9MWFNocLyy2yzmdv9v55Q==,type:str]
    AUTHENTIK_DB_PASS: ENC[AES256_GCM,data:VFxxkcpFZgi/w9kNa8+MeZBxoW7rqc75b0c62f/xaWMNPP954BXYL3bDapW9VERb4Q==,iv:VLynttpVQQngDFpmOGi8PsVATn01X5Xaxk2Z6Fa+mHQ=,tag:iI3Mb1a1wLlA2yd1Jva7Aw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:7lV3Wr730BhyKA==,iv:Opbyjq8QVNUHp+8U4yft5BOa61AHBCMPwGr3M+6/Tks=,tag:+Pe2r4QPUa7UjyW7yUg6JA==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:IsE3dr5AarufpKl+3w==,iv:GYZwqtR2ENDFKroerfv9tRAKdYD7+ln9Z01C7MB5nE4=,tag:Z5v0fLyCuGDKRykSHxyOMA==,type:str]
    RUNNER_TOKEN: ENC[AES256_GCM,data:0fevpdLz+6o8FIprbRKYEsHBR4F9s95mcR57l9c6nf/LzMqwvUC/gA==,iv:wczy3hrE/1hBcrR0sz+E5F7mcUNE8M7mv49u9y/bZf8=,tag:2aq7F0mHr+xgEFkpa7qcYg==,type:str]
    FORGEJO_INSTANCE_URL: ENC[AES256_GCM,data:r1LYk7jqpP7dl1eKldbWHYSHEFlAgRQS,iv:1u1JtjwLZ8PDxYc0+o8JY17z9XgptNrQx77KzYsVFss=,tag:W4mA78njHdUsA6cL+PCLcw==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dlBwNUEwOVlDRFR6dTlK
            b3BOS01JalVya1FBOHVrT2xLT3RhVVFZd1hvCnhBdUIxNi9FTjkyV1JhTStRSVZB
            N1pwNXZYWkkyNE9pdlk2U25Ma2ZsTU0KLS0tIFFnamlRWmJUYUE4SnlycTE4VEZk
            OGg0djNiTFU1MDI1SUUxRzBjTXFpa3MKPHH5a1BRqj0nD0oKzJoQWKf98PvX5jpS
            WXrqsXdvgCo77LdXTKnT7THBwe8sDA97NVQiEWJ2gsd4qDbbfop28A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T19:28:43Z"
    mac: ENC[AES256_GCM,data:ti3SrlAbMsRLlgbnnXndqqjC50x+2gzo+guo3kEkTJ57tIz2e1YsLNBreeHxy3ekok/+gBWJz1nzGQZYPmk/NG3i0CHUIs94nlNgcKFjmx3s2KiiqjK2WL0fUcR21YHlkdo1U1pXXCgPmbjf+7PmNjkUOIqJzBo0YChY/m0kqkA=,iv:kUAEPzzhoM8jK3/G789zI+Kf49E42iqA6HCODO+U4i8=,tag:LGSsxoD+RFLMSGHcssJFQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
