apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:1VgxWQ4xD7/orAmr,iv:HW7wm6QWsvTpNONC3bgDIXwi0BR5SKLxWQ0hpk6D7Yw=,tag:Erfbvg1Pwv4EGB4X3wPCPg==,type:str]
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:UTaoI3bfS4jYpaTU,iv:87uuBIM7oQaOgY1UUCY3jyACuAJ5j2YCkVrAZ6Cfv6c=,tag:OvzrBbmUe33yQxywV0XkLw==,type:str]
    MYSQL_PASSWORD: null
    GHOST_DB_PASSWORD: ENC[AES256_GCM,data:chkKXXbRTrgeX8kFhcw3IT7xyGV+yJA85/CEy/EsBfKTMrLpR9zp7P4vNZLRsbaOiQrQpqYpedit2szvS/eUGftARZHcBS35oLi8JvtvOP4=,iv:PBTMOXfe8R2MyqsgOmGZwwiZZihFs7ggzCsJSVFesww=,tag:u1nRuFdOcPs8Gz/Cr+bLnQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:7lV3Wr730BhyKA==,iv:Opbyjq8QVNUHp+8U4yft5BOa61AHBCMPwGr3M+6/Tks=,tag:+Pe2r4QPUa7UjyW7yUg6JA==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:IsE3dr5AarufpKl+3w==,iv:GYZwqtR2ENDFKroerfv9tRAKdYD7+ln9Z01C7MB5nE4=,tag:Z5v0fLyCuGDKRykSHxyOMA==,type:str]
    RUNNER_TOKEN: ENC[AES256_GCM,data:0fevpdLz+6o8FIprbRKYEsHBR4F9s95mcR57l9c6nf/LzMqwvUC/gA==,iv:wczy3hrE/1hBcrR0sz+E5F7mcUNE8M7mv49u9y/bZf8=,tag:2aq7F0mHr+xgEFkpa7qcYg==,type:str]
    FORGEJO_INSTANCE_URL: ENC[AES256_GCM,data:Y4vji/XxrNm5WpXSYQ1OcG5DNgCVsDR8Yg==,iv:p6s9X0xzgXwGxwtGV/XsHJkojbT5M2IJupg+PmNjXOo=,tag:HruMdHrRqKpOZumPvLHLig==,type:str]
    MATRIX_CLIENT_SECRET: ENC[AES256_GCM,data:nutnzK0lf5l3fPIg9EP8pzcJwcEEMaMnIUmoku1xo3w=,iv:az8ALpzPiC7VGbIrRklIVp8aSg3HhQ1Kgd+BeLx2dnc=,tag:A1G0ReCLcAQHvm/Xc6WAew==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dlBwNUEwOVlDRFR6dTlK
            b3BOS01JalVya1FBOHVrT2xLT3RhVVFZd1hvCnhBdUIxNi9FTjkyV1JhTStRSVZB
            N1pwNXZYWkkyNE9pdlk2U25Ma2ZsTU0KLS0tIFFnamlRWmJUYUE4SnlycTE4VEZk
            OGg0djNiTFU1MDI1SUUxRzBjTXFpa3MKPHH5a1BRqj0nD0oKzJoQWKf98PvX5jpS
            WXrqsXdvgCo77LdXTKnT7THBwe8sDA97NVQiEWJ2gsd4qDbbfop28A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T13:59:45Z"
    mac: ENC[AES256_GCM,data:acTkyURJmb8KPdLzCNFzMXANKOcMxw/qM7CTsOdHMjssEdHahPs4rt3jVJgQorJlwa7oUbRFZ0IKRKrVEzt0lVWKSFfaYYMuPIYoghUGnwewhLNN7bycqfrOAQN6I4HGYRf3UpZxszu3V8316D4rfwh0bo4hHqVAQzmW7dxOMm8=,iv:FDYOiEPf+6wW0NYB0i8A36X9nMysvcA5Iv9hfqd3Ssc=,tag:4bh+w2Evz/d2kJdyvzc+kQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
