apiVersion: v1
kind: Secret
metadata:
    name: maxmind-license
    namespace: network
stringData:
    account_id: ENC[AES256_GCM,data:CUNcplLd3g==,iv:wyAzYgp9D4v46FEy5Dq7ajsqCg8ghAtdFIhw2kAv9xY=,tag:KmzlZaenc7PMEIh+qKL6PQ==,type:str]
    license_key: ENC[AES256_GCM,data:cJSnDSwzu4/nwqNwTDBvTsnxxK7EoBZJyAhzOAr2BxKrLzFwKcl6/g==,iv:tY7YdKK46Fnc4qH/bP8Z4DXtYvNgfBCa1s9+R6L61rs=,tag:ZMKBiHMM4XQ2Aui9T1/8Bg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNTB1MnNaUnZjOXdoUE9D
            NElQS2d4M3F2cFRDbW1Da0dhMXBRMXMyckJFCkF4N0lGNEM2QWtvSVJGM3NsdllN
            V0srNVVzTlhML1ZXRmI2bmw5WnRqUWsKLS0tIFRLTC8yQm1lQmxIdXo1SXFMYnRs
            aWpQakt4VTlzb2Nka0tiUDZiOXUwMTQKFdZiptbnZvXJVvwSy87WHXz1wuKkiOIX
            1ZDyA8bVI93p+/Y/NIrItdN4JuvNVMiBCLzYjMB29x4wirTmCqDNBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T16:51:33Z"
    mac: ENC[AES256_GCM,data:kyTx+6Dis8mB4VkoZoSsHs+jyM0h7LFEaX3vkAwHNAtUDCfdPuyldRaEVUCO1GM5hSK0FKTkPnehEZdUl9z0AjhzBxlYf7r2fw63JlMSVsbIlGZcgaAMkciaunyw/kZEufhePD0ENjEOrRy85orwHfFP7YNC4Tp+u7XKcyG3PVg=,iv:F/kTeeVkU1b4wAxgHYZ+vzwc1MjHrVJ54NzHNPUsurA=,tag:F77OY3G78RuZ1VvRKUdyuQ==,type:str]
    version: 3.13.0
