---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: geo-allowlist
  namespace: network
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-external
  authorization:
    defaultAction: Deny
    rules:
      - name: allow-trusted-ips
        action: Allow
        principal:
          clientCIDRs:
            - 46.224.13.115/32 # albdev
            - 91.98.37.31/32 # sujiba
            - 10.0.0.0/8
            - 192.168.0.0/16
      - name: deny-high-risk-countries
        action: Deny
        principal:
          headers:
            - name: x-geo-country
              values:
                - "CN"  # China
                - "RU"  # Russia
                - "KP"  # North Korea
                - "IR"  # Iran
                - "BR"  # Brazil
                - "IN"  # India
                - "VN"  # Vietnam
                - "NG"  # Nigeria
                - "PK"  # Pakistan
                - "BD"  # Bangladesh
