apiVersion: v1
kind: Secret
metadata:
    name: mel-site-secret
    namespace: selfhosted
stringData:
    database__connection__password: ENC[AES256_GCM,data:pv1nHYjHbBf7wCx1tm4aBDarBU2W0dORs1wrkmIMHUWd0+staM0bScn4+nw/NZLEiEVpUQHQfAXPqgP6RyjxjpPPKHd0L0pWhFs43defTO9dRC0YhD2yag==,iv:uXQZ6fstFUNj0xFxzVr3tIQaW+DoSeQhMFd7sDt3zd8=,tag:RbNIuPsBkJEyl0O6MTWkmQ==,type:str]
    admin__url: ENC[AES256_GCM,data:b9i0o5T6ZtZgv8qFnnuxS9wxfpWzvO7TgiwMLIz4,iv:Ge65Yv/rK7MwoQXepoVsY/k9AcR8paPnesbHPexpqKE=,tag:M9QxP/AWjTE38Bl0gMm62g==,type:str]
    url: ENC[AES256_GCM,data:zcNpHxAUtWDs1xRlRGvaV9QsAehQP+Zj,iv:NEjqNbZq+2SNoxrtRotf2D/vPhA0L1FFf3yJ3NBZ9+s=,tag:LI4mrdLTyG7xd5PAH27z5g==,type:str]
    mail__transport: ENC[AES256_GCM,data:C9JruQ==,iv:TiZnG2ugf0JCD8ESgp5kief3Wfkk8mW8y79u1wazZgU=,tag:+MvuR4fqEaiLoxibKzaQeQ==,type:str]
    mail__from: ENC[AES256_GCM,data:0CSbWkoR/IvsqFGTm2SQBcPzBSkJ,iv:srRgn5O9f0GiTZ6CnqQDQDFgdpdDKxDZfBqc81v7x9I=,tag:Zo2O1Cn1Z+NBl6dQ/fWydg==,type:str]
    mail__options__service: ENC[AES256_GCM,data:XZUARsYEuw==,iv:O1c4luj0iSb85vy+GSkiDoHUE06aSKD3g00XVukTS40=,tag:0xxmt0lLS5kOLJ1REkSqQQ==,type:str]
    mail__options__host: ENC[AES256_GCM,data:Rnw6EqY6hGcYhUA74joJW4gs+j5raS3aYYKeHJP70QhENSCH,iv:0fAQ7qaVzznQTfyn2gScZfVyo2CCRF3au0QXWNUSnp0=,tag:sauS6t3qhlEP5sDAG0oRMw==,type:str]
    mail__options__port: ENC[AES256_GCM,data:CpflNg==,iv:RDf7CswhaLtTlzxq2vxv+3oE2rmbXoEagtO/HqE06u4=,tag:ZqW3XINpb62f7AjLjbnAQA==,type:str]
    mail__options__secure: ENC[AES256_GCM,data:FgHr2Kc=,iv:noPSoeePxEh4FaOJMKCZ/EV4RxE068p9TnPTHHIP1h4=,tag:72HLawE93OC9C+Gc81tDuA==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGhnZDdjR1VkYWhrRXJx
            SmRtV1plWUNmL2ZlMTNwbGErRVB4SDRLcUI4CkFMQ0NEVStvUUVMR2hnSTdCUHha
            ek1JcEN6U3lDWkFjSCtIem1JdEltYzgKLS0tIHZtYWVweXdsR0hxSmswQ0hnUTRz
            VDNKWlowS1VXZURES0dJMzRQaWRhQ3cKQFvSLEyCn3WbsD+wCbM4OwuSkHrAr3i1
            fYsM2EhWu/knKGh/zYYqzKpDyV+tjPmvjvI8wWpkZ4RFGTVL8WT/rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T23:11:54Z"
    mac: ENC[AES256_GCM,data:3jlp+MooY9IC79/U0cnaBUQz6emjuL/20nWAv9CXm5slEiedffJDMoaEAFPcrDoZmy3WmB5Hp08t5P4W4ThBePQtjY03EP19iz98jcPFgS7pHUurTTsb4pVS0J+QTQM7qjTZufZc5YG+ZaGkZizRwE7clNY5KMaEY1wIusw2/qU=,iv:i1zdKQe7qbrX365H3vb2SxO3GEr1rf3CcjyyRHffY/A=,tag:AnTHltkrU99lzrUzahVw2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
