apiVersion: v1
kind: Secret
metadata:
    name: mel-site-secret
    namespace: selfhosted
stringData:
    database__connection__password: ENC[AES256_GCM,data:pv1nHYjHbBf7wCx1tm4aBDarBU2W0dORs1wrkmIMHUWd0+staM0bScn4+nw/NZLEiEVpUQHQfAXPqgP6RyjxjpPPKHd0L0pWhFs43defTO9dRC0YhD2yag==,iv:uXQZ6fstFUNj0xFxzVr3tIQaW+DoSeQhMFd7sDt3zd8=,tag:RbNIuPsBkJEyl0O6MTWkmQ==,type:str]
    admin__url: ENC[AES256_GCM,data:b9i0o5T6ZtZgv8qFnnuxS9wxfpWzvO7TgiwMLIz4,iv:Ge65Yv/rK7MwoQXepoVsY/k9AcR8paPnesbHPexpqKE=,tag:M9QxP/AWjTE38Bl0gMm62g==,type:str]
    url: ENC[AES256_GCM,data:zcNpHxAUtWDs1xRlRGvaV9QsAehQP+Zj,iv:NEjqNbZq+2SNoxrtRotf2D/vPhA0L1FFf3yJ3NBZ9+s=,tag:LI4mrdLTyG7xd5PAH27z5g==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGhnZDdjR1VkYWhrRXJx
            SmRtV1plWUNmL2ZlMTNwbGErRVB4SDRLcUI4CkFMQ0NEVStvUUVMR2hnSTdCUHha
            ek1JcEN6U3lDWkFjSCtIem1JdEltYzgKLS0tIHZtYWVweXdsR0hxSmswQ0hnUTRz
            VDNKWlowS1VXZURES0dJMzRQaWRhQ3cKQFvSLEyCn3WbsD+wCbM4OwuSkHrAr3i1
            fYsM2EhWu/knKGh/zYYqzKpDyV+tjPmvjvI8wWpkZ4RFGTVL8WT/rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T22:50:09Z"
    mac: ENC[AES256_GCM,data:zUy0ErId4l9J2R/QaW60hAXnakQoooxp8IeMNrDvZ4JWLoaz0SRJmCBSBo0+Gx5SSRLLLOAsfPtztXxHTuheblNj1NBOSj0ydheUtJs7pxSCUxbjn4mBjmW3MDXTJazK+r8kjeHngkY9sRVrDhXByK+WnW4RZ5M3lhH2faBudy8=,iv:tQir4rchXaVMe5BAc3HDSQNFaKGCDifUW/V1XyCUhcI=,tag:ME2zFTwqE8Kmg4VPd0p8Ww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
