apiVersion: v1
kind: Secret
metadata:
    name: mel-site-secret
    namespace: selfhosted
stringData:
    database__connection__password: ENC[AES256_GCM,data:pv1nHYjHbBf7wCx1tm4aBDarBU2W0dORs1wrkmIMHUWd0+staM0bScn4+nw/NZLEiEVpUQHQfAXPqgP6RyjxjpPPKHd0L0pWhFs43defTO9dRC0YhD2yag==,iv:uXQZ6fstFUNj0xFxzVr3tIQaW+DoSeQhMFd7sDt3zd8=,tag:RbNIuPsBkJEyl0O6MTWkmQ==,type:str]
    admin__url: ENC[AES256_GCM,data:vlUq0C2zyOnIngsJtMwtBv4Eqa6DAg==,iv:e0JQ+kZ7FGlgLGwokc/7V6Rdo64Ke08Le2Wt5o2r8tk=,tag:H889xJgRYjm5hPCQETlt+w==,type:str]
    url: ENC[AES256_GCM,data:Fv3DislcR9zjXZrVgFdDXA==,iv:GpNpkNAtlwGmkuVLgyJK9kA/g0iLpYeX4aqAES5hEwU=,tag:PIzXEkAUFErtyJ39llzbHQ==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGhnZDdjR1VkYWhrRXJx
            SmRtV1plWUNmL2ZlMTNwbGErRVB4SDRLcUI4CkFMQ0NEVStvUUVMR2hnSTdCUHha
            ek1JcEN6U3lDWkFjSCtIem1JdEltYzgKLS0tIHZtYWVweXdsR0hxSmswQ0hnUTRz
            VDNKWlowS1VXZURES0dJMzRQaWRhQ3cKQFvSLEyCn3WbsD+wCbM4OwuSkHrAr3i1
            fYsM2EhWu/knKGh/zYYqzKpDyV+tjPmvjvI8wWpkZ4RFGTVL8WT/rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T22:33:34Z"
    mac: ENC[AES256_GCM,data:WU/iWe6v9hb3idi7ksm6nw81guQtbXatGqnJR0ZYaW3i/R0uOar6SYygpz6iFgg10yqpkNqjyz03xif8iL3dX/qupSzHQuXGyJBYaVnrJvGGNtBPv9jjgEHcrvBGMcbTM+iEuHLoLAulROnqCw+DOUpXaZqV6AISiBn9WQQTJ0M=,iv:Px/1WvLz4VJmYTj0MQr2N+R6rBGIR2Amhl0hWNzDWGk=,tag:N6gBhRxqgC0PEDXwrW3Lbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
