---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: nextcloud
  interval: 1m
  path: ./kubernetes/hcloud/apps/selfhosted/nextcloud/app
  components:
    - ../../../../components/valkey
  postBuild:
    substitute:
      APP: nextcloud
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud-collabora
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: nextcloud-collabora
  interval: 15m
  path: ./kubernetes/hcloud/apps/selfhosted/nextcloud/collabora
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  wait: false