---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-code-local
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: openebs-hostpath