apiVersion: v1
kind: Secret
metadata:
    name: netcup-secret
    namespace: cert-manager
stringData:
    customer-number: ENC[AES256_GCM,data:3o5cqwz8,iv:wMPV9RVdBK27JM+1P3KzVieldEGtX31OYHRdmiT9czk=,tag:LHHg/OjRnAUXQlSYrcdXRA==,type:int]
    api-key: ENC[AES256_GCM,data:X09wjoz68Am4sTYYHCLDw3cKFpc/SQ1mr5auObKpjW0zl29bl+pm8J30tpVgG6jSync=,iv:ypy7UxKj1KnVegTOCRDHvbTWhbmwVq0/2QmHKpYrR6M=,tag:LG3SwMIg5czAKOBmcpP7rw==,type:str]
    api-password: ENC[AES256_GCM,data:ngDsMqprQ+Vpblj6MSGHgMg1t+uCeHGH0poaHU8xNKRzNe4wp0kayM3Kk5nFcrpu/uo=,iv:qbU3uM2bVmta8+cN5LTvd6NjiAmYjpx2H1pq3EFU+IA=,tag:fxdgsEZdZx3tNwEFfXFjKA==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNTB1MnNaUnZjOXdoUE9D
            NElQS2d4M3F2cFRDbW1Da0dhMXBRMXMyckJFCkF4N0lGNEM2QWtvSVJGM3NsdllN
            V0srNVVzTlhML1ZXRmI2bmw5WnRqUWsKLS0tIFRLTC8yQm1lQmxIdXo1SXFMYnRs
            aWpQakt4VTlzb2Nka0tiUDZiOXUwMTQKFdZiptbnZvXJVvwSy87WHXz1wuKkiOIX
            1ZDyA8bVI93p+/Y/NIrItdN4JuvNVMiBCLzYjMB29x4wirTmCqDNBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T13:43:50Z"
    mac: ENC[AES256_GCM,data:WZ2OjQp71k3+uxyh52I9hiUfJk0xvHdSmlbgnWp4Rawk+ZSpT451P9dJ/rSL0RcTKoP3uxnSNIsZy2oFNqySiABW5C5E4iTwcX9ecBG32BC2hfNL4ewJPD8vXmom2qaqE99+c/AQwWNmQImwtCqNuY95MzbYiHIzaEmfxs9tIRM=,iv:Y7rwmtfqQ2JbTXYs+aCioFb0As9TbBdZ/ZnH8VIWwS8=,tag:Ke7FyiL4IYlmP+OMc8TmMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
