---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: arrs
spec:
  interval: 15m
  path: ./kubernetes/home/apps/selfhosted/arrs/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: arrs
      VOLSYNC_CAPACITY: 100Gi
      VOLSYNC_GID: "1000"
      VOLSYNC_UID: "1000"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: configarr
spec:
  interval: 15m
  path: ./kubernetes/home/apps/selfhosted/arrs/configarr
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      VOLSYNC_GID: "1000"
      VOLSYNC_UID: "1000"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  wait: false