apiVersion: v1
kind: Secret
metadata:
    name: tailscale-secret
    namespace: network
stringData:
    TS_AUTHKEY: ""
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNTB1MnNaUnZjOXdoUE9D
            NElQS2d4M3F2cFRDbW1Da0dhMXBRMXMyckJFCkF4N0lGNEM2QWtvSVJGM3NsdllN
            V0srNVVzTlhML1ZXRmI2bmw5WnRqUWsKLS0tIFRLTC8yQm1lQmxIdXo1SXFMYnRs
            aWpQakt4VTlzb2Nka0tiUDZiOXUwMTQKFdZiptbnZvXJVvwSy87WHXz1wuKkiOIX
            1ZDyA8bVI93p+/Y/NIrItdN4JuvNVMiBCLzYjMB29x4wirTmCqDNBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T11:31:31Z"
    mac: ENC[AES256_GCM,data:zpZKQ+J+Tj4DQEEjfRPrX4DU41Y57nOq1rwHgmSsK4VqWVuXsuFdwM26wmlJYVWnUz8/DZ1GezOw081A6O07y55DilL3i1iH19OqtiBGsoz0TXvPGxHS7z3UulVxPgtAhdToYDGxIprBVBJwYdvFVXIUNIXeog5vM3igPQWvgzo=,iv:f1wuQ97K3dZnE5Y44qStPJpWYxpnJ38x2oumXc9Iwc4=,tag:gONGfOZsCMmcRWYNB5n5LA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
