---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgresql-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-hostpath
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photo-nfs
spec:
  storageClassName: photo-nfs
  capacity:
    storage: 60Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${SECRET_MEDIA_SERVER}"
    path: /volume1/photos
  mountOptions:
    - nfsvers=4
    - nconnect=16
    - soft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photo-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: photo-nfs
  resources:
    requests:
      storage: 60Ti