apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: selfhosted
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:p9To/PsoUIUipV2icSyavtgQkJ5nVTc4xtekI8leauqaztn4O6XBfCD+eg==,iv:qlmoh+Gt8+VN+zXQXMDT6m1LXOO392S9xBMgB3Galu0=,tag:hhlFir6C0eYr7MFH+mjr2A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:2/ZXSbO0xyr0lqusxLuOKU/fBJqWIpkhQakU3uQOnBua0fwY1u1StOKYVw==,iv:g3j9n+rHzdR163XnD7sSkiHLWAC630uB4vVtLnbbI+g=,tag:INpA62HcMWTBPvVRfahloQ==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGhnZDdjR1VkYWhrRXJx
            SmRtV1plWUNmL2ZlMTNwbGErRVB4SDRLcUI4CkFMQ0NEVStvUUVMR2hnSTdCUHha
            ek1JcEN6U3lDWkFjSCtIem1JdEltYzgKLS0tIHZtYWVweXdsR0hxSmswQ0hnUTRz
            VDNKWlowS1VXZURES0dJMzRQaWRhQ3cKQFvSLEyCn3WbsD+wCbM4OwuSkHrAr3i1
            fYsM2EhWu/knKGh/zYYqzKpDyV+tjPmvjvI8wWpkZ4RFGTVL8WT/rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T21:55:40Z"
    mac: ENC[AES256_GCM,data:8SkQBARmDmSXMElkfxQIRhotBvJYTcQgtLRZKLoIEqTjhU0faLcpsM3IBdGwqdzi5TMLvdB55T1spzuWs/xVCy34i7q0YP+JtB2rSRuGk1O9479+oP3qf2nP5xhRunfluQwTJ36px8o4uAQkCBCPaQFHpyfq0qSx0qT9JSBdsG8=,iv:PjmUBiB5RldmnMCis8Ifx1ATKnz+jqGequV6hjOrtbk=,tag:qJuagwqxGy97y5lplvqdJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
