---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: immich-postgresql-data-backup
spec:
  sourcePVC: immich-postgresql-data
  trigger:
    schedule: "0 16 * * *" # Daily at 4 PM UTC or 5 PM CET
  kopia:
    capacity: 10Gi
    compression: zstd
    cleanupCachePVC: true
    cleanupTempPVC: true
    copyMethod: Snapshot
    enableFileDeletion: true
    moverSecurityContext:
      runAsUser: ${VOLSYNC_UID}
      runAsGroup: ${VOLSYNC_GID}
      fsGroup: ${VOLSYNC_GID}
    repository: volsync-kopia-secret
    retain:
      daily: 7        # Keep 7 daily snapshots
      weekly: 4       # Keep 4 weekly snapshots
