apiVersion: v1
kind: Secret
metadata:
    name: litellm
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:yhRxr9CQJKwa/9ki7Xw2USoEuDREFBOzvi5zJOB+kUv37szhvcj0JJGD6DP3jIf3xYoRLWfarGgsEVQM5Evn4ppYuA==,iv:oF5kM/BiJ4leRMIgTXFSw+B5OkohvbqnGu+TzTnUmgw=,tag:dlL/l+dX8T4pj6K2tYpntw==,type:str]
    OPENCODE_GO_API_KEY: ENC[AES256_GCM,data:fT7Irps3Iwq2ArfGx3P8lwQnvpFdKgL50WlohIyNlI2m9nbro2jyt1xHCyPFvGc91oax25ZSzG3ljP1bk2HAz3hNeA==,iv:ki1TjfKJrxqaJYKAe4S1NnlpbVUK2BNG9sAAjcd3Xjs=,tag:kmzw4Pc7YzfEVGVK8wdekg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGhnZDdjR1VkYWhrRXJx
            SmRtV1plWUNmL2ZlMTNwbGErRVB4SDRLcUI4CkFMQ0NEVStvUUVMR2hnSTdCUHha
            ek1JcEN6U3lDWkFjSCtIem1JdEltYzgKLS0tIHZtYWVweXdsR0hxSmswQ0hnUTRz
            VDNKWlowS1VXZURES0dJMzRQaWRhQ3cKQFvSLEyCn3WbsD+wCbM4OwuSkHrAr3i1
            fYsM2EhWu/knKGh/zYYqzKpDyV+tjPmvjvI8wWpkZ4RFGTVL8WT/rw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T19:50:38Z"
    mac: ENC[AES256_GCM,data:4yoa/yf9O4/NDZsnpg9MkkHpLSouApHAHcmbPvFZNBoHyb42M2LtO2dT+3svMB3xEZGqFnbMNJzE2ZYYIIH9tnXfnNZol47czQgf7gQQw6yQi+u7FCDSusIuYf6nHWVNEn+iK+H6Apyjrdikt0PJrKpp4224XUR2x9xmUNRbCnA=,iv:Qjb+x24dQ4xmaHbQTO6vmsE/sfEB6RffIHHXak+PGyg=,tag:/qVLKMXLn7EDGr28DJqklA==,type:str]
    version: 3.13.3
