---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bentopdf
spec:
  chartRef:
    kind: OCIRepository
    name: bentopdf
  interval: 15m
  values:
    controllers:
      bentopdf:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/alam00000/bentopdf-simple
              tag: 2.3.0@sha256:8e18ebc13b3da714cf593dae724d97f01cc16f25c6e253b8be2ca926568a27f0
            env:
              TZ: ${TIMEZONE}
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 512Mi

    service:
      app:
        ports:
          http:
            port: 8080

    route:
      app:
        hostnames: ["pdf.${CLUSTER_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
            
    persistence:
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /var/cache/nginx
            subPath: cache
          - path: /etc/nginx/tmp
            subPath: tmp