---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: athena
spec:
  allowedNamespaces:
    all: true
  backend:
    s3:
      auth:
        secretRef:
          name: kopiur-repository-secret
          namespace: kopiur-system
      bucket: homelab-backup
      endpoint: "${SECRET_MEDIA_SERVER}:9000"
      region: us-east-1
      tls:
        disableTls: true
  encryption:
    passwordSecretRef:
      name: kopiur-repository-secret
      namespace: kopiur-system
      key: KOPIA_PASSWORD
  scheduleDefaults:
    timezone: Europe/Berlin