---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: symphonia
spec:
  chartRef:
    kind: OCIRepository
    name: symphonia
  interval: 15m
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
 
    controllers:
      symphonia:
        replicas: 2
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: code.albdev.cloud/lab/symphonia
              tag: 0.7.3
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 100Mi

    service:
      app:
        controller: symphonia
        ports:
          http:
            port: 8080

    route:
      app:
        hostnames: ["symphonia.${CLUSTER_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https

    persistence:
      tmp:
        type: emptyDir
        sizeLimit: 1Gi