---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy
spec:
  loadBalancerIPs: true
  interfaces:
    - ^enp[0-9]+s[0-9]+$
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool
spec:
  allowFirstLastIPs: "Yes"
  blocks:
    - cidr: 192.168.178.3/32
    - cidr: 192.168.178.4/32
    - cidr: 192.168.178.230/32
    - cidr: 192.168.178.231/32
    - cidr: 192.168.178.241/32
    - cidr: fd74:56aa:152e:21::80/128
    - cidr: fd74:56aa:152e:21::81/128