apiVersion: v1
kind: Secret
metadata:
    name: mariadb-secret
    namespace: selfhosted
stringData:
    MARIADB_PASSWORD: ENC[AES256_GCM,data:ogWtN8cLCMLdqx6IgKHHBWOK/GfpYf9I5eCmjLPAiNUQQwhYfiDsaOCzzZc/dzChCG6FtuUXMpo0XfD+YB2fDtAncTJSln3W4rfMPl0fVJvs65U/Gkn5IQ==,iv:CfgmPMfCYppUDEtn4VnFoqV7xl3I+L4cNsPJLcDwuhI=,tag:nKu0j6f/S3bGY+w1pmJcFA==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:+Q+eyZBaATtadJN9tHN2X69YFakI7gMTGLzaOgVwUfrdLxFKU/RzMrRIiUf8nOJG+RzvOrgGNOZJx4e1CPjyUEhAG/ocyG2oANLQMvtq25J0jAtNhRNjbw==,iv:3s7JkqSyie83hh4IukFd18Z8YOh6MAfNFfo8O//4cwY=,tag:2NhnzKe21W+PaYJFRVCyLw==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGhnZDdjR1VkYWhrRXJx
            SmRtV1plWUNmL2ZlMTNwbGErRVB4SDRLcUI4CkFMQ0NEVStvUUVMR2hnSTdCUHha
            ek1JcEN6U3lDWkFjSCtIem1JdEltYzgKLS0tIHZtYWVweXdsR0hxSmswQ0hnUTRz
            VDNKWlowS1VXZURES0dJMzRQaWRhQ3cKQFvSLEyCn3WbsD+wCbM4OwuSkHrAr3i1
            fYsM2EhWu/knKGh/zYYqzKpDyV+tjPmvjvI8wWpkZ4RFGTVL8WT/rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T22:12:10Z"
    mac: ENC[AES256_GCM,data:Nhf4u50ADXmMoqmoeX+dS1FJhy6UvQMcmJa8aSCBJpH/9dTD2dScW+y9TpJPzZvXqPCO3Sto9mY3TqqqsWO1TdKesyoyjp2WJEwmbFfkz5pS1Hr7jpHeeylm/TLX3IzN9IXKCi/yLxb6GFdG4ay9sxGV2Oamfxj/8lrLfpA6dDc=,iv:3QtMDCwFAgkZAc4BXlA53ej6APcz08bzyjz+OcLNI+8=,tag:x2t7kUeQOkWu0de0KZLkKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
