apiVersion: v1
kind: Secret
metadata:
    name: matrix-secrets
    namespace: selfhosted
stringData:
    PG_PASSWORD: ENC[AES256_GCM,data:bc0m0fJSAlAfws8tF9/lxEgLYIhPlbhNh7u5eKPpLQQ=,iv:LSWg3iEvIcZgbwzMLh54ATzyJJ8U7xlYWpd5gvbW8RM=,tag:0TBBLT4vjrTq9kWmuqlu3Q==,type:str]
    SMTP_PASSWORD: ""
    CLIENT_SECRET: ENC[AES256_GCM,data:84G2DDxkfBaXeHLAuimzWZT1OKCD9kg/wdVar+pZ6vs=,iv:mG221AiyRXOI5BbkyA2WBgZg7dIpzJi6K61+nk7wUoo=,tag:TnP2J325Knn3+BHFEKKqLg==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGhnZDdjR1VkYWhrRXJx
            SmRtV1plWUNmL2ZlMTNwbGErRVB4SDRLcUI4CkFMQ0NEVStvUUVMR2hnSTdCUHha
            ek1JcEN6U3lDWkFjSCtIem1JdEltYzgKLS0tIHZtYWVweXdsR0hxSmswQ0hnUTRz
            VDNKWlowS1VXZURES0dJMzRQaWRhQ3cKQFvSLEyCn3WbsD+wCbM4OwuSkHrAr3i1
            fYsM2EhWu/knKGh/zYYqzKpDyV+tjPmvjvI8wWpkZ4RFGTVL8WT/rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T17:26:40Z"
    mac: ENC[AES256_GCM,data:4HdeVg/OdhS1b4SSPvz50aUdtCoIF/soiyZOmfcrEys9T5+2LG2tXvUGqQcCcoPd0r6GuvMNk2xIcquXtIsVlkk7YUGmBqnnkbmh/nF1W3Xuyu0raVjUTc7u7Hs4KGLBs+ekp79v6VdTYs59xf3XS2rC6wlrNmi0EKTkzkwthNA=,iv:O7po+fnJQyUyvBv+IVQJEYUmHq8zGbeWg/JSEqS8PZo=,tag:2GVvZ4Vt0XOfzxeMi2oeFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
