apiVersion: v1
kind: Secret
metadata:
    name: matrix-secrets
    namespace: selfhosted
stringData:
    PG_PASSWORD: null
    SMTP_PASSWORD: ""
    CLIENT_SECRET: ENC[AES256_GCM,data:84G2DDxkfBaXeHLAuimzWZT1OKCD9kg/wdVar+pZ6vs=,iv:mG221AiyRXOI5BbkyA2WBgZg7dIpzJi6K61+nk7wUoo=,tag:TnP2J325Knn3+BHFEKKqLg==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGhnZDdjR1VkYWhrRXJx
            SmRtV1plWUNmL2ZlMTNwbGErRVB4SDRLcUI4CkFMQ0NEVStvUUVMR2hnSTdCUHha
            ek1JcEN6U3lDWkFjSCtIem1JdEltYzgKLS0tIHZtYWVweXdsR0hxSmswQ0hnUTRz
            VDNKWlowS1VXZURES0dJMzRQaWRhQ3cKQFvSLEyCn3WbsD+wCbM4OwuSkHrAr3i1
            fYsM2EhWu/knKGh/zYYqzKpDyV+tjPmvjvI8wWpkZ4RFGTVL8WT/rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T17:06:53Z"
    mac: ENC[AES256_GCM,data:HD+SspV4xRMjikMMi456IFSV+3891PqcZfymr+aIDdHoG/PXQQggyWdMG+0xYN4fCG1kAQlm+x6hgoXk5BU6pHB9/WlSEag9EEbSqRk2i1iDd4xzsF9JbovVpE5+coarBxbGngqYn5xZD/+xjC++P2krpW+JSqlxA7JuRihh0hA=,iv:Z4i9qv2JT0Nu8iJMv5bfD66HHsJweSRRK3ArBgRbNt0=,tag:vL6NyVX/+zyBYE8AsmtfvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
