apiVersion: v1
kind: Secret
metadata:
    name: netbird-api-token
    namespace: network
stringData:
    NB_API_KEY: ENC[AES256_GCM,data:8I3rorZQ7EM6/JhdAcyZo0/4O11uok1vjh4qknEJCmuFhxIvB/rotQ==,iv:ZEjvRVa6ML15Rn2wK2biOo7wyKlTKBuzAfe6/uepjL8=,tag:XYqZtrDi7KJrso4ca1p55Q==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNTB1MnNaUnZjOXdoUE9D
            NElQS2d4M3F2cFRDbW1Da0dhMXBRMXMyckJFCkF4N0lGNEM2QWtvSVJGM3NsdllN
            V0srNVVzTlhML1ZXRmI2bmw5WnRqUWsKLS0tIFRLTC8yQm1lQmxIdXo1SXFMYnRs
            aWpQakt4VTlzb2Nka0tiUDZiOXUwMTQKFdZiptbnZvXJVvwSy87WHXz1wuKkiOIX
            1ZDyA8bVI93p+/Y/NIrItdN4JuvNVMiBCLzYjMB29x4wirTmCqDNBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T23:11:23Z"
    mac: ENC[AES256_GCM,data:NK3g2HxiCjL0FfhGSYCiWk1/OnrTrJ5cehPLWsVMUcH2YzACnCb6Cz+KvM1PAuFqnUsyJxPFxvVXep9Rtgwmr8qfiFWxgSw+/dyXXCt+sg0VL/X26L/BHGdDGACKwUSrewUU0XWzXhsgBkN/xpQpUIjJwbtsRlfKjMcWFT6xvoI=,iv:u9N+sglTb7Oz1+4NK3csQ6huhwE8epGHPfYOBTe0s5c=,tag:IiWNDwoPG5UUoNILcnjZZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
