apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:HnI3bym79svzAw==,iv:ZGr/gJpwjTOIREX5m86w3wnrIWxUvACFGIB28RqlLYQ=,tag:+jX4EOldB/8yJiznhBrzdA==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dlBwNUEwOVlDRFR6dTlK
            b3BOS01JalVya1FBOHVrT2xLT3RhVVFZd1hvCnhBdUIxNi9FTjkyV1JhTStRSVZB
            N1pwNXZYWkkyNE9pdlk2U25Ma2ZsTU0KLS0tIFFnamlRWmJUYUE4SnlycTE4VEZk
            OGg0djNiTFU1MDI1SUUxRzBjTXFpa3MKPHH5a1BRqj0nD0oKzJoQWKf98PvX5jpS
            WXrqsXdvgCo77LdXTKnT7THBwe8sDA97NVQiEWJ2gsd4qDbbfop28A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T22:50:13Z"
    mac: ENC[AES256_GCM,data:bda+KtOyocMBZxDt78kxqUB1CoyQhiE9k14G8dm6Vw52sXlZmiL8yoYLXQYyVhqijmUSRvL6kum63/PHF17qMUbjr3K7mB6s5ekyQe8nn8rrf63lr/wsj9SKhHJ2a7/4t6sUGH1IkUAAo3bxvyQ6QPdGZFkT5yKJ6BKFnXgf9OU=,iv:3ZVKemheTAQ297vNy2dLwrp+gFwl4GWBRmVuiLmRZCM=,tag:544tSR9pmo3YuEnAVzmsMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
