apiVersion: v1
kind: Secret
metadata:
    name: netbird-api-token
    namespace: network
stringData:
    NB_API_KEY: ENC[AES256_GCM,data:D3I8vmkAjZoAGfNYj9jOfQLfXLVnF4g6xO1/QJlcM+LqhE5k,iv:OzMhoUiqrWv7y/omWMBNQf2QU3/3Gkk8QTVj4E+JiNs=,tag:JtiYdGNXxmsOa4iBoWEH+A==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNTB1MnNaUnZjOXdoUE9D
            NElQS2d4M3F2cFRDbW1Da0dhMXBRMXMyckJFCkF4N0lGNEM2QWtvSVJGM3NsdllN
            V0srNVVzTlhML1ZXRmI2bmw5WnRqUWsKLS0tIFRLTC8yQm1lQmxIdXo1SXFMYnRs
            aWpQakt4VTlzb2Nka0tiUDZiOXUwMTQKFdZiptbnZvXJVvwSy87WHXz1wuKkiOIX
            1ZDyA8bVI93p+/Y/NIrItdN4JuvNVMiBCLzYjMB29x4wirTmCqDNBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T22:45:02Z"
    mac: ENC[AES256_GCM,data:dcQIWEBUEZVXjx6IFAf2UHqTQuPSmZRULMrdAOzksljUGCtgX/H9eUYj2Mj7B0pmIjprNzzU/6mURLosgNDMtGT3iMG1hqg3biH1ZGtAaX7Nt3ragecduNa/QJ1+ZmoXR6Uk8ilsTdypp24TrKqvFqOvcWPfxOM6FT61RT5OLRY=,iv:y3P9dQ9eoM/vrConLxs/uKhmkl0nNSredLJ0SMZgWPQ=,tag:/h6VrZV/IE6xf5TV8Tw9DA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
