apiVersion: v1
kind: Secret
metadata:
    name: netbird-secret
    namespace: network
stringData:
    NB_API_KEY: ENC[AES256_GCM,data:OK+BQN3ygqsiH4V/QaurWtggvJKoQh5bMnITEW3E1fDCZpdX,iv:OHYe7OhSMmXk1JlIGCHV7XsUabqBpzLddrQAU/GgGaI=,tag:yWmUFgdnTkzkbTgKWW05kQ==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNTB1MnNaUnZjOXdoUE9D
            NElQS2d4M3F2cFRDbW1Da0dhMXBRMXMyckJFCkF4N0lGNEM2QWtvSVJGM3NsdllN
            V0srNVVzTlhML1ZXRmI2bmw5WnRqUWsKLS0tIFRLTC8yQm1lQmxIdXo1SXFMYnRs
            aWpQakt4VTlzb2Nka0tiUDZiOXUwMTQKFdZiptbnZvXJVvwSy87WHXz1wuKkiOIX
            1ZDyA8bVI93p+/Y/NIrItdN4JuvNVMiBCLzYjMB29x4wirTmCqDNBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T17:55:27Z"
    mac: ENC[AES256_GCM,data:lLOT+GIQYpgXWSs2q4bnFmzP0teN9RAaKaanSjWU1Ca5bKVxTE71uDEHyPWKs3Wn3j3buqkH2WVbc7S8VQwjI0UiF4WRFX6Wtg0Q6h9ZB7zDLuHbo4bUaXCuJaOWGU0dnQD7EQzU00a9d7WPE2lTfVAdqezhq0akcA+QhMWrXXE=,iv:/2JnJYWCGsSpwwEZml9E0LzudP/HTDx3jKGlKwFQa2I=,tag:r9Clrhndvm9MaJRt3Dq2Tw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
