apiVersion: v1
kind: Secret
metadata:
    name: netbird-secret
    namespace: network
stringData:
    SETUP_KEY: ENC[AES256_GCM,data:IKOmGM2UOAfjorIVZKnGidHB4xlOJ6pJR43SqQreEWoqeW6d,iv:xkdSl3B6U34Qw4Ty0r7bUbrw8lzO6OJOBTMz9CU3J7E=,tag:VGmRP0nwcQXbeq2YfZd08A==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNTB1MnNaUnZjOXdoUE9D
            NElQS2d4M3F2cFRDbW1Da0dhMXBRMXMyckJFCkF4N0lGNEM2QWtvSVJGM3NsdllN
            V0srNVVzTlhML1ZXRmI2bmw5WnRqUWsKLS0tIFRLTC8yQm1lQmxIdXo1SXFMYnRs
            aWpQakt4VTlzb2Nka0tiUDZiOXUwMTQKFdZiptbnZvXJVvwSy87WHXz1wuKkiOIX
            1ZDyA8bVI93p+/Y/NIrItdN4JuvNVMiBCLzYjMB29x4wirTmCqDNBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T22:33:42Z"
    mac: ENC[AES256_GCM,data:VKS7/25d45AV1WcSnvrTOXPXj0lWgGZQzrXGVraeXgRZEmXFUZ0YCbsi/d1OKxUhuwWsjwtRvcZPP22O/zTkr6sgD+2njxBzOn9JChNH56rXdeIeCdIjzVCuvSICbF/f7ssULilPwJ0w9ypmXL8RdzET/pUQ+2tUwpUvbX4PQxM=,iv:7P1fKJAZ+7b2BiQmeEry6tofoLrr2P05LvXbQXrSSt8=,tag:U1nRGG70LRqcf+KFNwjz/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
