---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: int-albdev-tls
spec:
  secretName: int-albdev-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: int.albdev.cloud
  dnsNames:
    - int.onji.space
    - "*.int.onji.space"
    - int.albdev.cloud
    - "*.int.albdev.cloud"
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ext-albdev-vpn-tls
spec:
  secretName: ext-albdev-vpn-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: ext.albdev.cloud
  dnsNames:
    - ext.onji.space
    - "*.ext.onji.space"
    - ext.albdev.cloud
    - "*.ext.albdev.cloud"
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always