apiVersion: v1
data:
  signing_key: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNEVlVUSEMreW8zVzIrMW1qTW9BOWxxTnVjcjdtN3QwK3psYXRieWJaWVVoUUFBQUppQ2NadHJnbkdiCmF3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDRFZVVEhDK3lvM1cyKzFtak1vQTlscU51Y3I3bTd0MCt6bGF0YnliWllVaFEKQUFBRURjbml5ZGRzai9wZjd1TWQ5L2Z5cHFzajdKQWdJYVJXNFhSY3NTUkJ4ZWZOVlJNY0w3S2pkYmI3V2FNeWdEMldvMgo1eXZ1YnUzVDdPVnExdkp0bGhTRkFBQUFEMlp2Y21kbGFtOHRjMmxuYm1sdVp3RUNBd1FGQmc9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
  signing_key.pub: c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSU5WUk1jTDdLamRiYjdXYU15Z0QyV28yNXl2dWJ1M1Q3T1ZxMXZKdGxoU0YgZm9yZ2Vqby1zaWduaW5nCg==
kind: Secret
metadata:
  name: forgejo-signing-key
  namespace: forgejo
