apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: home-automation
stringData:
    zigbee_ext_pan_id: ENC[AES256_GCM,data:JrR843H9YZIH0xn629yR/kwE3IwMD09ojdZTyBG5jSfDiPWblw==,iv:boT/SA/7gILc5O4fcLoHXymlpf6Gmy28NP3Y+eEanC8=,tag:+XZexXtE7/nOoZeON0r27w==,type:str]
    zigbee_network_key: ENC[AES256_GCM,data:q/jgnlm5FiSFzqfEaWOTrJ8nAIkG1HRtOckHsHww5EV9YZXQ9MzD+DZxnnc/Bvpm/OdGl84P5GcOAjeldpMKaoyMIlKJJvWB,iv:MC6kyhx4sDalvhhGRayPp+TI+OKtwTvJWm0QORSB/Fo=,tag:77AAAjD40vvZGQRUZGKnAg==,type:str]
    zigbee_pan_id: ENC[AES256_GCM,data:c8Wrlzo=,iv:XlKxWgw+UdGJMm3Z2XrNYLgnLjGHqGEIFj5xrSdEnB4=,tag:3GtROIQBc60Ylozl4d69SA==,type:int]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGhnZDdjR1VkYWhrRXJx
            SmRtV1plWUNmL2ZlMTNwbGErRVB4SDRLcUI4CkFMQ0NEVStvUUVMR2hnSTdCUHha
            ek1JcEN6U3lDWkFjSCtIem1JdEltYzgKLS0tIHZtYWVweXdsR0hxSmswQ0hnUTRz
            VDNKWlowS1VXZURES0dJMzRQaWRhQ3cKQFvSLEyCn3WbsD+wCbM4OwuSkHrAr3i1
            fYsM2EhWu/knKGh/zYYqzKpDyV+tjPmvjvI8wWpkZ4RFGTVL8WT/rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T18:00:09Z"
    mac: ENC[AES256_GCM,data:ctFT+xDTVsXsNq4T+GWQfBAJHw8zIZxW7APmdN2BXvLFi9OGJ7VFuyuxugo08hvvLvBW1asaABEZJvdXtVLZPbDFW4se3dwcj5Q7V8Rsd219ccER3+lO3fttNUbxIiN5gPWI07svnlb/D1QhcAsiHNPkij6D8QZ3tfZtaYvUTQo=,iv:Pe6/0vx/RAMNOLXWI+FjkSTHAuV12LvW7OjCxW2l2+w=,tag:nsxFBJbVXZauF1Y90hPREw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
