apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: home-automation
stringData:
    zigbee_ext_pan_id: ENC[AES256_GCM,data:JrR843H9YZIH0xn629yR/kwE3IwMD09ojdZTyBG5jSfDiPWblw==,iv:boT/SA/7gILc5O4fcLoHXymlpf6Gmy28NP3Y+eEanC8=,tag:+XZexXtE7/nOoZeON0r27w==,type:str]
    zigbee_network_key: ENC[AES256_GCM,data:q/jgnlm5FiSFzqfEaWOTrJ8nAIkG1HRtOckHsHww5EV9YZXQ9MzD+DZxnnc/Bvpm/OdGl84P5GcOAjeldpMKaoyMIlKJJvWB,iv:MC6kyhx4sDalvhhGRayPp+TI+OKtwTvJWm0QORSB/Fo=,tag:77AAAjD40vvZGQRUZGKnAg==,type:str]
    zigbee_pan_id: ENC[AES256_GCM,data:wWkuuo4=,iv:7aPRjQt7WaE9C/OdaL0LkMD0KxYwXgSqfwFtL5t9c1w=,tag:w/a4ueu8ANL0Eo8P+jp9Kg==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGhnZDdjR1VkYWhrRXJx
            SmRtV1plWUNmL2ZlMTNwbGErRVB4SDRLcUI4CkFMQ0NEVStvUUVMR2hnSTdCUHha
            ek1JcEN6U3lDWkFjSCtIem1JdEltYzgKLS0tIHZtYWVweXdsR0hxSmswQ0hnUTRz
            VDNKWlowS1VXZURES0dJMzRQaWRhQ3cKQFvSLEyCn3WbsD+wCbM4OwuSkHrAr3i1
            fYsM2EhWu/knKGh/zYYqzKpDyV+tjPmvjvI8wWpkZ4RFGTVL8WT/rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T07:58:48Z"
    mac: ENC[AES256_GCM,data:DvFP5unHL+pw1Uhg41XY/IQA5auSB9Pur6lcbY18sWUwAvPq39fIGXfCJA9e8xL+tsqUqCk+oNriX45sYOUhazL/gvTGMocWPE5Mz88sOE7u/0DdaYrNReXE7nA/MRQ4MrXyQAeHgjS78yQV0ReA5abBRRx+dNrmgBox1YT3QNs=,iv:x8VIS7ASJe6aQfH2q5e7/7XiDagU5fcstOY+SFkf/KE=,tag:IBk1TPQGlhsfsbaeS2da2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
