apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: home-automation
stringData:
    zigbee_ext_pan_id:
        - ENC[AES256_GCM,data:X9bW,iv:jHoZq5PfdkDZHwMpe9MRiS9HJ8ShbisH+KjgTvq/ZSk=,tag:ObBfg2LmH7qJeF2m5OXzlw==,type:int]
        - ENC[AES256_GCM,data:fXQ=,iv:guLVhn0vflVKGToTqUn8K3cH/Fbet3k5K6BcogiPi1s=,tag:78ofa/GILbb8zLFaJI0r+Q==,type:int]
        - ENC[AES256_GCM,data:KDcO,iv:Z1sE/v/xrhLhO052vDBWERMoB+/Ek+7WHYhVm/JI1cE=,tag:2Z2uwKqv3Fa6AFvMElgReg==,type:int]
        - ENC[AES256_GCM,data:HhQ=,iv:Wx7Q7QA0qE6daBxD9mz79SXHrK7+deoMm/cnbi0tlfM=,tag:qJSJrQz7xzqZIy30MSftcg==,type:int]
        - ENC[AES256_GCM,data:rOg=,iv:im6OHaw/l5OdXpRWVsy9Na08HC4OCcqspgrn7kdKU18=,tag:HWTX6hCKtfxkTU6ZiH2oOQ==,type:int]
        - ENC[AES256_GCM,data:b/2p,iv:wyDcSMO4JwSz3/vb+NuxCm2BMaGuuNNmnuk3KAR54+Y=,tag:leKxULX9v5mx3kx35XeHog==,type:int]
        - ENC[AES256_GCM,data:1yXa,iv:4fezUTN3s0EabW54pal/vTbSZtXYwIUhvmlMFGEL1Js=,tag:FOvjQ+Carn0Eck9EBFjxZg==,type:int]
        - ENC[AES256_GCM,data:pCzH,iv:P0AwvO0KVCPaytt1KXi2q8/SnbCkGPfcMhu18jiZ8CQ=,tag:Dac1BKMDl4aL26+3MHf5zg==,type:int]
    zigbee_network_key:
        - ENC[AES256_GCM,data:Aok=,iv:qX8urRV15gQSnItughHuEs5DdVK9RL8glYagPwEByag=,tag:AxctkNz2+1AIVLHUbEZ+Fw==,type:int]
        - ENC[AES256_GCM,data:VdpR,iv:OYWN2qdDAesyRvpx1ihRusYm9DqvBUXl4KyI996pw/Q=,tag:kjOAo2JOEfNmAoHc5Nhbpg==,type:int]
        - ENC[AES256_GCM,data:9TA=,iv:FIBwRbtr5JDdU1SJR5w+xe7MtBqX4F6uFfWVUMG10R8=,tag:dNlvpV1rT81jswf/avLNFg==,type:int]
        - ENC[AES256_GCM,data:5Mc=,iv:t3rsv9x0ctu5jN0bmJI3xDKlCZWhW9fV/TT7Uzzd2eY=,tag:70KmRxYglNqY9F3KtV1log==,type:int]
        - ENC[AES256_GCM,data:sCY=,iv:qevytjsGh9siR9l0d3tHWalBk51HA2vlTTP65OJpH5U=,tag:WN7xyfZkeFyymrDI9aWjXw==,type:int]
        - ENC[AES256_GCM,data:1No=,iv:yWR0GL9iB2HdFidONeufUmCFXbwo9JTUric5fdJzNZc=,tag:EVVc8Wnmxk+6Ss9nmDy/Iw==,type:int]
        - ENC[AES256_GCM,data:4F4=,iv:gr/DDTYBZgUIMUdGRzPXJyKRczqIMldz0M990p3I1rA=,tag:e4yUmolqJKXJ7Ud1Vhz2Mw==,type:int]
        - ENC[AES256_GCM,data:3BOS,iv:7Pz4gHrSa5xegNwVetikzZhfF8chWH4YkmxM+JGq3xM=,tag:efWCQRLh53wDznruEcVJ9Q==,type:int]
        - ENC[AES256_GCM,data:VXdg,iv:RzFL5BIuBAF3nv1kSbqoRIR3IhPTJZsLFnthhWcfI9Q=,tag:YnpDdH6QJboJNeNy7x+c4Q==,type:int]
        - ENC[AES256_GCM,data:1xs=,iv:saReQymNwwcvfuXgcOxURTHneB6Ds1QqYfP1NqK+CCA=,tag:WtFh8SItn79S8/oScFM/Qw==,type:int]
        - ENC[AES256_GCM,data:mmPB,iv:37Cwo0p4rYyyx9YFTndKtKwTleo2vBsguLMfOVuSOxI=,tag:NLEfXm+1yVoNCsnJj+IP/A==,type:int]
        - ENC[AES256_GCM,data:uKxG,iv:w9dplZr8thVJ0n6Z21XUlKnSWZQkNLZ2vShJiEqufEg=,tag:MVeeNSNGJZtWh6gQ+KnJAg==,type:int]
        - ENC[AES256_GCM,data:jPM=,iv:GfTWWeU6f0yhfasIHCs0t+qKkC7JEazyx6/k+flIYKo=,tag:r3/byzh28v+XtZxEyDohBg==,type:int]
        - ENC[AES256_GCM,data:+Ym6,iv:lVzHZUZtOALiznHmYpVPvGUhRwG8Rq6/mqbMpvNfZzE=,tag:tlSWxT+rMLKKNEDzAMcxRQ==,type:int]
        - ENC[AES256_GCM,data:ZUkY,iv:dedfu58+a/m+oAyj/ZYY8629XgSrteCW9SgdnMut+GI=,tag:0sHFPcRd+X2CPJXi8Gni5Q==,type:int]
        - ENC[AES256_GCM,data:njeL,iv:jSBiHF6cuJLZ2+cH8IRh3RjnRwGXSIP+paxSsi6DXsQ=,tag:bTCVIw+h+KE/bS8BzaOddw==,type:int]
    zigbee_pan_id: ENC[AES256_GCM,data:c8Wrlzo=,iv:XlKxWgw+UdGJMm3Z2XrNYLgnLjGHqGEIFj5xrSdEnB4=,tag:3GtROIQBc60Ylozl4d69SA==,type:int]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGhnZDdjR1VkYWhrRXJx
            SmRtV1plWUNmL2ZlMTNwbGErRVB4SDRLcUI4CkFMQ0NEVStvUUVMR2hnSTdCUHha
            ek1JcEN6U3lDWkFjSCtIem1JdEltYzgKLS0tIHZtYWVweXdsR0hxSmswQ0hnUTRz
            VDNKWlowS1VXZURES0dJMzRQaWRhQ3cKQFvSLEyCn3WbsD+wCbM4OwuSkHrAr3i1
            fYsM2EhWu/knKGh/zYYqzKpDyV+tjPmvjvI8wWpkZ4RFGTVL8WT/rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T17:18:10Z"
    mac: ENC[AES256_GCM,data:eAehSTECrBsPknSiv9n55wLPPWpRR1jUutsjQyGNNmaHS3pFG8W5iMaNROd1CpJONW1z+DWyS+vFNcAzke9jCwfImLFjagepudkE+1TYup6yhCohUw/U8g16Rq13OcHO1U3DaHeU2Q0nwKsZtDcTDBUopp5uvSEWVtKUpxoSmsI=,iv:6KQ/495mMKJnUqSOEUVZiTVPRWgV3+SZ8EG1dXs2azQ=,tag:hgeuF2wgUdrXVVTFa8MaTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
