apiVersion: v1
kind: Secret
metadata:
    name: netcup-secret
    namespace: cert-manager
stringData:
    customer-number: ENC[AES256_GCM,data:hW/JLJn4,iv:sp2a356VPjpbE22mD1cSM6M8qEzeU4v2xMmXo1vSYeg=,tag:9F5o+P4YfuU8z+nPRZJLiQ==,type:str]
    api-key: ENC[AES256_GCM,data:X09wjoz68Am4sTYYHCLDw3cKFpc/SQ1mr5auObKpjW0zl29bl+pm8J30tpVgG6jSync=,iv:ypy7UxKj1KnVegTOCRDHvbTWhbmwVq0/2QmHKpYrR6M=,tag:LG3SwMIg5czAKOBmcpP7rw==,type:str]
    api-password: ENC[AES256_GCM,data:ngDsMqprQ+Vpblj6MSGHgMg1t+uCeHGH0poaHU8xNKRzNe4wp0kayM3Kk5nFcrpu/uo=,iv:qbU3uM2bVmta8+cN5LTvd6NjiAmYjpx2H1pq3EFU+IA=,tag:fxdgsEZdZx3tNwEFfXFjKA==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNTB1MnNaUnZjOXdoUE9D
            NElQS2d4M3F2cFRDbW1Da0dhMXBRMXMyckJFCkF4N0lGNEM2QWtvSVJGM3NsdllN
            V0srNVVzTlhML1ZXRmI2bmw5WnRqUWsKLS0tIFRLTC8yQm1lQmxIdXo1SXFMYnRs
            aWpQakt4VTlzb2Nka0tiUDZiOXUwMTQKFdZiptbnZvXJVvwSy87WHXz1wuKkiOIX
            1ZDyA8bVI93p+/Y/NIrItdN4JuvNVMiBCLzYjMB29x4wirTmCqDNBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T13:49:23Z"
    mac: ENC[AES256_GCM,data:xxCndzF8tL90ag+KSjEUsBO6yCq7Z28cyMTjW1Z6amOXOCkqKgL8mGVCUIc6jwFKYHSOYz3HjOFYuA3+gfwmdJIaInSrO5iHvMHgZZJqJ76dDSfg6qXhuiPf2c+5gVHdVQTHIctPpLHMsMh376AMrBe8T+gjSTdMZnCK4cLdLzQ=,iv:RSOvHCX/kKvM0ltu7omRmrSwrepovd12UXc1n4oo0Kc=,tag:yTlnxtKC8M41+Zdk4MxS+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
