---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  chart:
    spec:
      chart: nextcloud
      version: 8.5.2
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  interval: 1h
  values:
    deploymentAnnotations:
      secret.reloader.stakater.com/reload: nextcloud-secret
    image:
      repository: nextcloud
      tag: 32.0.1-fpm-alpine
      flavor: fpm-alpine
    phpClientHttpsFix:
      enabled: true
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        cert-manager.io/private-key-rotation-policy: Always
        cert-manager.io/private-key-algorithm: "ECDSA"
        cert-manager.io/private-key-size: "384"
        traefik.ingress.kubernetes.io/router.middlewares: "network-traefik-middleware-chain-no-auth@kubernetescrd"
        
      tls:
        - secretName: cloud-onji-tls
          hosts:
            - cloud.onji.space
    nextcloud:
      host: cloud.onji.space
      extraEnv:
        - name: REDIS_HOST
          value: dragonfly.databases.svc.cluster.local
        - name: REDIS_DATABASE
          value: "2"
      existingSecret:
        enabled: true
        secretName: &secret nextcloud-secret
        usernameKey: nc-admin
        passwordKey: nc-admin-pw
      mail:
        enabled: true
        fromAddress: no-reply
        domain: ${SECRET_DOMAIN}
        smtp:
          host: smtp-relay.network.svc.cluster.local
          secure:
          port: 2525
          authtype:
          name:
          password:
      defaultConfigs:
        redis.config.php: false
      configs:
        local.config.php: |-
            <?php
            $CONFIG = array(
              'trusted_proxies' => array(
                '127.0.0.1',
                '10.0.0.0/8',
              ),
              'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
              'default_phone_region' => 'DE',
              'auth.bruteforce.protection.enabled' => true,
              'maintenance_window_start' => 1,
              'simpleSignUpLink.shown' => false,
              'overwrite.cli.url' => 'https://cloud.onji.space',
            );
      phpConfigs:
        uploadLimit.ini: |
          upload_max_filesize = 16G
          post_max_size = 16G
          max_input_time = 3600
          max_execution_time = 3600
      hooks:
        post-installation: |-
          php occ maintenance:repair --include-expensive
          php occ db:add-missing-indices
          php occ db:add-missing-columns
          php occ db:add-missing-primary-keys
        before-starting: |-
          # disable unneceserry apps
          for appname in activity circles systemtags federation privacy \
              nextcloud_announcements announcementcenter support survey_client \
              user_status weather_status dashboard app_api
            do
            php occ app:disable "$appname"
          done
        post-upgrade: |-
          php occ maintenance:repair --include-expensive
          php occ db:add-missing-indices
          php occ db:add-missing-columns
          php occ db:add-missing-primary-keys
    collabora:
      enabled: true

      collabora:
        aliasgroups:
          - host: "https://cloud.onji.space:443"
        extra_params: --o:ssl.enable=false --o:ssl.termination=true

      server_name: collabora.onji.space

      existingSecret:
        enabled: true
        # name of existing Kubernetes Secret with collboara admin credentials
        secretName: nextcloud-secret
        usernameKey: "colla-username"
        passwordKey: "colla-password"

      ingress:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          cert-manager.io/private-key-rotation-policy: Always
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-traefik-middleware-chain-no-auth@kubernetescrd"
        hosts:
          - host: collabora.onji.space
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - hosts:
              - collabora.onji.space
            secretName: collabora-tls

    cronjob:
      enabled: true
      cronjob:
        schedule: "0 */4 * * *"
    persistence:
      enabled: true
      existingClaim: nextcloud-local
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        memory: 2Gi
    startupProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 360
      successThreshold: 1
    livenessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    nginx:
      enabled: true
      image:
        repository: public.ecr.aws/nginx/nginx
        tag: "1.29.3"
      config:
        default: true
      resources:
        requests:
          cpu: 50m
          memory: 20Mi
        limits:
          memory: 100Mi
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: *secret
        databaseKey: pg-db
        hostKey: pg-host
        passwordKey: pg-password
        usernameKey: pg-username
    redis:
      enabled: false
    metrics:
      enabled: false
      https: true
      serviceMonitor:
        enabled: false
