---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-local
  namespace: selfhosted
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
  storageClassName: openebs-hostpath