apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: selfhosted
stringData:
    nc-admin: ENC[AES256_GCM,data:gkh3ZjE0aWpE3w==,iv:9Gx//pV70FMfKuEIbHt5FrzHnrXnLmTKY1vvrki2BDI=,tag:YD132zkF2cXVMoY/ASN1Ew==,type:str]
    nc-admin-pw: ENC[AES256_GCM,data:HqipQfTC7Ob50Yf5K474sBv/V5/0TB0BcKiKI3KPyoyjYYR74bWz2GrcX1leuuF4o80EeKlyEoxHuBoO2JrZUyKqRd0FDIA89Jn10uRtPq4=,iv:pnulhyELILXjS3Gkdxe7jQz9UYM6lhPhZFtZhF0KIio=,tag:OMOkNCwU28pXIejvsUTb2A==,type:str]
    pg-username: ENC[AES256_GCM,data:PvLajytxstpbDxO+BZM=,iv:mYT6T4BHDuuAac/wOXzBePGN4cfiRFelbjaIXUhQDVU=,tag:fPfTPYs7RiNGqHSRj1GUvg==,type:str]
    pg-password: ENC[AES256_GCM,data:BXC1WNgH4BzIFyTP0VvKxwsWCWsjQxSD1n6rQrjmuGTK6d3TzG188gNJoWaEUgQ3zNluA7ChZPDHTg7UbOrALz/fvrk60pnrMylRTXrPLNo=,iv:jDfgdaNzrcpAmbCy85+kI3IyII8DPEjKiMy8gjc18xI=,tag:ybbgEVE2djb2zw4b2tAMbQ==,type:str]
    pg-host: ENC[AES256_GCM,data:aj1F+0onb1sIIWKn5lhML13J7KWD2pbo/lwvMu3pmYzkTE2E49wknybUd6168A==,iv:Qoj2RecGlOM3ZwwmDK3MS+CV6odgMqMy1W2gjM/8uwU=,tag:tfeeItcUBGaT76qTahJz2g==,type:str]
    pg-db: ENC[AES256_GCM,data:TPtVyal33tRWHTLMHuk=,iv:0DEiTTgR3JVP/5Wd6WMvqLpJ+Y7YVYAGOf0fnnSSFmM=,tag:M/7UEfdVjfiMtoVaDUNF5g==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNTB1MnNaUnZjOXdoUE9D
            NElQS2d4M3F2cFRDbW1Da0dhMXBRMXMyckJFCkF4N0lGNEM2QWtvSVJGM3NsdllN
            V0srNVVzTlhML1ZXRmI2bmw5WnRqUWsKLS0tIFRLTC8yQm1lQmxIdXo1SXFMYnRs
            aWpQakt4VTlzb2Nka0tiUDZiOXUwMTQKFdZiptbnZvXJVvwSy87WHXz1wuKkiOIX
            1ZDyA8bVI93p+/Y/NIrItdN4JuvNVMiBCLzYjMB29x4wirTmCqDNBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T20:21:45Z"
    mac: ENC[AES256_GCM,data:FrPk2YNYMWw+BY6L9GhMP1XLKSPb8USoqv+aBYLlA6RL8UQ4B1tkkpElC8vShZECYKtGej43bUgoX7U6lRNmxHaD5laRfTgDFpTCmvYvRnky1tDWb5o33ohZh3WzXqXR1LZMbmpg7brNSPZvoMdENWHeQKpVG+4Yu9YcHtxzEbo=,iv:KqWwO21cVKB5cJ4nIURUEQNXCPuE6yGLGjipzR3TJ/w=,tag:Asf54EmVhQGIL3c9cwoUGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
