---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seerr
spec:
  interval: 30m
  timeout: 5m
  path: ./kubernetes/home/apps/selfhosted/seerr/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: seerr
      VOLSYNC_UID: "1000"
      VOLSYNC_GID: "1000"
      VOLSYNC_CLAIM: seerr-data
      VOLSYNC_CAPACITY: 5Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  wait: false