apiVersion: v1
kind: Secret
metadata:
    name: configarr
    namespace: selfhosted
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:410yco0DkY+kEVjf6kEp9mM8NBR3wBq8R1sftO052Z8=,iv:C+QUjnOluuMfm4VbuJlxCXkJvrr6Mf1cScQv2kWy+Mk=,tag:DtjxRVGniDDliInZKHAPBw==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:HZPhOvEYYHzQ49VqNSIAjhOsyyiqlUbixDBBZhgmRL0=,iv:sQJYYnOLe6nsTVXfJDWXIMytp4so4q/i0+BrUs/AKps=,tag:KeUCMQyuFctN9A9LP7tezQ==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGhnZDdjR1VkYWhrRXJx
            SmRtV1plWUNmL2ZlMTNwbGErRVB4SDRLcUI4CkFMQ0NEVStvUUVMR2hnSTdCUHha
            ek1JcEN6U3lDWkFjSCtIem1JdEltYzgKLS0tIHZtYWVweXdsR0hxSmswQ0hnUTRz
            VDNKWlowS1VXZURES0dJMzRQaWRhQ3cKQFvSLEyCn3WbsD+wCbM4OwuSkHrAr3i1
            fYsM2EhWu/knKGh/zYYqzKpDyV+tjPmvjvI8wWpkZ4RFGTVL8WT/rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T16:46:09Z"
    mac: ENC[AES256_GCM,data:B8/RezYZ5CchaV4Erm720uMYhPEcWakhbfOJuOdhp65FWcQJnjaXdNxaOgZltryhMkCOoBPoibWiz1WWlGTn7nPI8Bkzj80ZTUoJG3LOv3hBjY4UWSgo8Cj+v3dg+obKLSu0HIqbcNTmczsprIhEB4cYU21cbDG0eJ8MWs4TDLw=,iv:r5hHJZMODkAl+h5I85rc964oWZ9EnDodKngCIX35YKg=,tag:H/Z4uPugnkHlzQXH0jUCMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
