---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- opencode-go-deepseek-v4-flash.yaml
- opencode-go-glm-5-2.yaml
- opencode-go-kimi-k2-6.yaml
- opencode-go-kimi-k2-7-code.yaml
- opencode-go-kimi-k3.yaml
- opencode-go-minimax-m3.yaml
- opencode-go-qwen3-8-max.yaml
- 
