---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
#  - ./nextcloud/ks.yaml
  - ./it-tools/ks.yaml
  - ./headscale/ks.yaml
  - ./freshrss/ks.yaml
  - ./ntfy/ks.yaml