---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tuppr
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.1.25@sha256:eeb7df9d5208652612cd3f26a5c9da93798e7754b5ed5a4caed162ca201a2c21
  url: oci://ghcr.io/home-operations/charts/tuppr