---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tuppr
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.1.26@sha256:77fdd38ed9d8b32720fe6e731a28a8d3f93d5c343b2eef3614b8882d70df4fe4
  url: oci://ghcr.io/home-operations/charts/tuppr