---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: littlelink
spec:
  chartRef:
    kind: OCIRepository
    name: littlelink
  interval: 30m
  values:
    controllers:
      littlelink:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/techno-tim/littlelink-server
              tag: latest@sha256:e84ea9d93b60362cf9e292dba43adb604e375d9206d5fcf1de6bb766a20aabd1
            env:
              TZ: ${TIMEZONE}
              META_TITLE: Symphonia Costumes
              META_DESCRIPTION: Symphonia Costumes Link Page
              META_KEYWORDS: Devops
              META_AUTHOR: Symphonia Costumes
              META_LANG: en
              META_INDEX_STATUS: all
              OG_SITE_NAME: Symphonia Costumes Links
              OG_TITLE: Symphonia Costumes Links
              OG_DESCRIPTION: A collection of all of my relevant links
              OG_URL: https://symphonia.${SECRET_DOMAIN}
              FAVICON_URL: https://p16-pu-sign-no.tiktokcdn-eu.com/tos-no1a-avt-0068c001-no/40bd186a5b28d1affcffe7021d50e341~tplv-tiktokx-cropcenter:1080:1080.jpeg?dr=10399&refresh_token=53fe626e&x-expires=1766502000&x-signature=VQi1EbJI5D5has6qLq35YNDUv64%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=81f88b70&idc=no1a
              AVATAR_URL: https://p16-pu-sign-no.tiktokcdn-eu.com/tos-no1a-avt-0068c001-no/40bd186a5b28d1affcffe7021d50e341~tplv-tiktokx-cropcenter:1080:1080.jpeg?dr=10399&refresh_token=53fe626e&x-expires=1766502000&x-signature=VQi1EbJI5D5has6qLq35YNDUv64%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=81f88b70&idc=no1a
              AVATAR_2X_URL: https://p16-pu-sign-no.tiktokcdn-eu.com/tos-no1a-avt-0068c001-no/40bd186a5b28d1affcffe7021d50e341~tplv-tiktokx-cropcenter:1080:1080.jpeg?dr=10399&refresh_token=53fe626e&x-expires=1766502000&x-signature=VQi1EbJI5D5has6qLq35YNDUv64%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=81f88b70&idc=no1a
              NAME: "Symphonia"
              THEME: Dark
              BIO: "Costume Artist | Wig Artist | Embroidery | Cosplay"
              BUTTON_ORDER: INSTAGRAM,BLUESKY,TIKTOK,KOFI,EMAIL
              CUSTOM_BUTTON_TEXT: Support me on Ko-fi
              CUSTOM_BUTTON_URL: https://ko-fi.com/symphoniacostumes
              CUSTOM_BUTTON_COLOR: "#000000"
              CUSTOM_BUTTON_TEXT_COLOR: "#ffffff"
              CUSTOM_BUTTON_ALT_TEXT: MY Ko-fi
              CUSTOM_BUTTON_NAME: "KOFI"
              CUSTOM_BUTTON_ICON: "fa-brands fa-gitlab"
              INSTAGRAM: https://www.instagram.com/symphoniacostumes
              BLUESKY: https://bsky.app/profile/stephcalation.bsky.social
              TIKTOK: https://www.tiktok.com/@symphoniacostumes
              EMAIL: symphonia@naoalb.org
              EMAIL_TEXT: Email me!
              FOOTER: Symphonia © 2025-Present
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 100Mi
    service:
      app:
        controller: littlelink
        ports:
          http:
            port: 3000

    ingress:
      app:
        className: traefik
        hosts:
          - host: "symphonia.albdev.cloud"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http