---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: littlelink
spec:
  chartRef:
    kind: OCIRepository
    name: littlelink
  interval: 15m
  values:
    defaultPodOptions:
      securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          runAsGroup: 65534
          fsGroup: 65534
          fsGroupChangePolicy: OnRootMismatch
          seccompProfile: { type: RuntimeDefault }
 
    controllers:
      littlelink:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/techno-tim/littlelink-server
              tag: latest@sha256:e84ea9d93b60362cf9e292dba43adb604e375d9206d5fcf1de6bb766a20aabd1
            env:
              TZ: ${TIMEZONE}
              META_TITLE: Symphonia Costumes
              META_DESCRIPTION: Symphonia Costumes Link Page
              META_KEYWORDS: Devops
              META_AUTHOR: Symphonia Costumes
              META_LANG: en
              META_INDEX_STATUS: all
              OG_SITE_NAME: Symphonia Costumes Links
              OG_TITLE: Symphonia Costumes Links
              OG_DESCRIPTION: A collection of all of my relevant links
              OG_URL: https://symphonia.albdev.cloud
              FAVICON_URL: https://files.albdev.cloud/apps/files_sharing/publicpreview/7Gitc7CtLsCXiHb?file=/&fileId=9189&x=3024&y=1964&a=true&etag=fe84cfcdcf07d577ffc501c43c4ba5d5
              AVATAR_URL: https://files.albdev.cloud/apps/files_sharing/publicpreview/7Gitc7CtLsCXiHb?file=/&fileId=9189&x=3024&y=1964&a=true&etag=fe84cfcdcf07d577ffc501c43c4ba5d5
              AVATAR_2X_URL: https://files.albdev.cloud/apps/files_sharing/publicpreview/7Gitc7CtLsCXiHb?file=/&fileId=9189&x=3024&y=1964&a=true&etag=fe84cfcdcf07d577ffc501c43c4ba5d5
              NAME: "Symphonia"
              THEME: Dark
              BIO: "Costume Artist | Wig Artist | Embroidery | Cosplay"
              BUTTON_ORDER: INSTAGRAM,BLUESKY,TIKTOK,KOFI,EMAIL
              CUSTOM_BUTTON_TEXT: Support me on Ko-fi
              CUSTOM_BUTTON_URL: https://ko-fi.com/symphoniacostumes
              CUSTOM_BUTTON_COLOR: "#000000"
              CUSTOM_BUTTON_TEXT_COLOR: "#ffffff"
              CUSTOM_BUTTON_ALT_TEXT: MY Ko-fi
              CUSTOM_BUTTON_NAME: "KOFI"
              CUSTOM_BUTTON_ICON: "fa-brands fa-paypal"
              INSTAGRAM: https://www.instagram.com/symphoniacostumes
              BLUESKY: https://bsky.app/profile/stephcalation.bsky.social
              TIKTOK: https://www.tiktok.com/@symphoniacostumes
              EMAIL: symphonia@naoalb.org
              EMAIL_TEXT: Email me!
              FOOTER: Symphonia © 2025-Present
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 100Mi

    service:
      app:
        controller: littlelink
        ports:
          http:
            port: 3000

    route:
      app:
        hostnames: ["symphonia.${CLUSTER_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https