---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./certificates.yaml
  - ./envoy.yaml
  - ./grafanadashboard.yaml
  - ./https-redirect.yaml
  - ./internal.yaml
  - ./podmonitor.yaml
  - ./vpn.yaml
  - ./waf.yaml