---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-volsync
  namespace: observability
type: Opaque
stringData:
  RESTIC_REPOSITORY: "s3:https://${S3_DOMAIN_EXTERNAL}/homelab-grafana"
  RESTIC_PASSWORD: ${SECRET_VOLSYNC_RESTIC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${SECRET_VOLSYNC_S3_ACCESS_KEY}
  AWS_SECRET_ACCESS_KEY: ${SECRET_VOLSYNC_S3_SECRET_KEY}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: grafana
  namespace: observability
spec:
  sourcePVC: grafana-pvc
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: grafana-volsync
    volumeSnapshotClassName: csi-local-hostpath
    cacheCapacity: 5Gi
    cacheStorageClassName: local-hostpath
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: local-hostpath
    accessModes: ["ReadWriteOnce"]
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    retain:
      hourly: 24
      daily: 7
      weekly: 5