---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: nextcloud-next
  namespace: databases
spec:
  cluster:
    name: postgres-cluster
  name: nextcloud-next
  owner: nextcloud-next
  extensions:
    - name: pg_trgm
    - name: citext