apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-next-db-owner
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:E0KPETw5Km3VuY4e/0c=,iv:SI2FjYOo2B30plCkkwGBN79SzaWmUf5kS+DZ8ePMFxM=,tag:ng9D2wZ1zegYNPHTSmSqVQ==,type:str]
    password: ENC[AES256_GCM,data:o7zZvLyEyvCvQBs84G5L8DVTg/Kq8AZ7OvnBtkFnJn34oCOTUnn89JUrr6UddTTuIuu/9ALWm8vEEYG9D7vGa2AK5f68cpy95XsouFNcFZY=,iv:jqjn99Q0hSd4u7G2fGfusd6mA9EdHx7ZtQmPnDt/rL8=,tag:bkMVufwFjhpW0wCQkOmKSQ==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvKzdyU083MjkzM1gxeWlk
            cGZ5SFZPLyttM0RRL2pxYVY0S1RTckkwK0RzCkdWbkM3WUhEc3ZhYTl1MktvaUdU
            aGU5ZU5jcnNzSEhRbVh2NzRJQWRlYXcKLS0tIE1XbmRob1g3djFMckNucUxEUmky
            RTh1dlpEVTlkd0xkb1hhVkw5eFhHc1kKi4RnpW6+aS7oVo6Xsd85rh74ZnDi9y10
            8kSNhqU39uesK2FXe94RndNmbjUBpzW6fGxkXtG58/nACF+mUcnIrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T15:42:26Z"
    mac: ENC[AES256_GCM,data:KkIbCUGbssHvkKNGc/4fT14vuToo+hVqGLvijd4niWSKrdJhb0pg2dQ2eeWMBxnAy7G5P3QxaSu3Q6WfkF0ve0M+YVMZ98NP36EyVUHozMhI9SL65Fflmi9SuU7Nhgc8VBfXH00Z818SMG8WxS7L4FozcYPw+b6QXJ0D8J31/Tc=,iv:y7+00+/czZYxPAdtTuOn6MJtNsFfcLQBZ6T7XqU+V2c=,tag:5yIZtG3+1fTkL4QSrX/1SQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
