apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-owner
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:1hn/ZdymZ+kN,iv:1JVeoP+GDukdwzsoPV6g1G2+FpXH5Kgz6PC0MAqytYY=,tag:UWzUBUlPMHZe3sIUhGubSA==,type:str]
    password: ENC[AES256_GCM,data:CBSQtHZS1rISqm2biagW9hxPoiGa+IDQiYfNxd6Oys/8JfOKXRVJEIsLW1QFYP9qWA==,iv:DHaP4eVtWeuendfg+7y15H+1WhNduvlrS0hOLbrtGxU=,tag:j6hNK3rjJ4vdWI1cwJi7uw==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvKzdyU083MjkzM1gxeWlk
            cGZ5SFZPLyttM0RRL2pxYVY0S1RTckkwK0RzCkdWbkM3WUhEc3ZhYTl1MktvaUdU
            aGU5ZU5jcnNzSEhRbVh2NzRJQWRlYXcKLS0tIE1XbmRob1g3djFMckNucUxEUmky
            RTh1dlpEVTlkd0xkb1hhVkw5eFhHc1kKi4RnpW6+aS7oVo6Xsd85rh74ZnDi9y10
            8kSNhqU39uesK2FXe94RndNmbjUBpzW6fGxkXtG58/nACF+mUcnIrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T22:21:09Z"
    mac: ENC[AES256_GCM,data:Wd1WkoTWFRcpWQXPkL/pPDcomMYPOms4041m9nDpL0dK2AF/6e8OwcGlbCFjpXQJOvtHWRRGEcGucjLo9QLhLpsLvEmvGp+ROhN3Hg2oT9bmXhA1twULO4+HhM1kHm48y1mylQOA30M5WI/LFAo44P0/mBMS+/IJ8Pg/sGcqb1c=,iv:15uBzindQTcOvYngW93ZrmW6+gLIwC+hzdzaHbdhpEY=,tag:0URR2MW4mENJdNaQj6zb7Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
