apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-owner
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:1hn/ZdymZ+kN,iv:1JVeoP+GDukdwzsoPV6g1G2+FpXH5Kgz6PC0MAqytYY=,tag:UWzUBUlPMHZe3sIUhGubSA==,type:str]
    password: ENC[AES256_GCM,data:CBSQtHZS1rISqm2biagW9hxPoiGa+IDQiYfNxd6Oys/8JfOKXRVJEIsLW1QFYP9qWA==,iv:DHaP4eVtWeuendfg+7y15H+1WhNduvlrS0hOLbrtGxU=,tag:j6hNK3rjJ4vdWI1cwJi7uw==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvKzdyU083MjkzM1gxeWlk
            cGZ5SFZPLyttM0RRL2pxYVY0S1RTckkwK0RzCkdWbkM3WUhEc3ZhYTl1MktvaUdU
            aGU5ZU5jcnNzSEhRbVh2NzRJQWRlYXcKLS0tIE1XbmRob1g3djFMckNucUxEUmky
            RTh1dlpEVTlkd0xkb1hhVkw5eFhHc1kKi4RnpW6+aS7oVo6Xsd85rh74ZnDi9y10
            8kSNhqU39uesK2FXe94RndNmbjUBpzW6fGxkXtG58/nACF+mUcnIrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T13:39:45Z"
    mac: ENC[AES256_GCM,data:+Ncb7jlS6+AL/UQn1/iq0/KWfoH0JzFADo+pF2BpHucSTLPYxXufqjTo+X3ThcU6gMkBT0jN21vTZ72K8oH8N1oNLrj+jLozLDeeNB+t4dnjsN6w9+eOIq4ozzZ6DMZivCOdn9Y3V4uIMEvEpjiUBKY2GWtv0EEt5RiysBur2Wc=,iv:8SG9cYK+zhBM+ZhDnWI8wHlUl3Jreca90ZD2oGwzzyo=,tag:fqpI6ZHM6BOfGiQHcwuFyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db-owner
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Gpw71vejAM2N,iv:KpRrArBsxhyzw1g+961RcDffj/eJ/zrewRgOx3qwIyY=,tag:YfJncrExCSqM4ppUPSYrSA==,type:str]
    password: ENC[AES256_GCM,data:o7zZvLyEyvCvQBs84G5L8DVTg/Kq8AZ7OvnBtkFnJn34oCOTUnn89JUrr6UddTTuIuu/9ALWm8vEEYG9D7vGa2AK5f68cpy95XsouFNcFZY=,iv:jqjn99Q0hSd4u7G2fGfusd6mA9EdHx7ZtQmPnDt/rL8=,tag:bkMVufwFjhpW0wCQkOmKSQ==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvKzdyU083MjkzM1gxeWlk
            cGZ5SFZPLyttM0RRL2pxYVY0S1RTckkwK0RzCkdWbkM3WUhEc3ZhYTl1MktvaUdU
            aGU5ZU5jcnNzSEhRbVh2NzRJQWRlYXcKLS0tIE1XbmRob1g3djFMckNucUxEUmky
            RTh1dlpEVTlkd0xkb1hhVkw5eFhHc1kKi4RnpW6+aS7oVo6Xsd85rh74ZnDi9y10
            8kSNhqU39uesK2FXe94RndNmbjUBpzW6fGxkXtG58/nACF+mUcnIrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T13:39:45Z"
    mac: ENC[AES256_GCM,data:+Ncb7jlS6+AL/UQn1/iq0/KWfoH0JzFADo+pF2BpHucSTLPYxXufqjTo+X3ThcU6gMkBT0jN21vTZ72K8oH8N1oNLrj+jLozLDeeNB+t4dnjsN6w9+eOIq4ozzZ6DMZivCOdn9Y3V4uIMEvEpjiUBKY2GWtv0EEt5RiysBur2Wc=,iv:8SG9cYK+zhBM+ZhDnWI8wHlUl3Jreca90ZD2oGwzzyo=,tag:fqpI6ZHM6BOfGiQHcwuFyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
