---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: ollama
  values:
    controllers:
      ollama:
        replicas: 1
        containers:
          app:
            image:
              repository: ollama/ollama
              tag: 0.13.5@sha256:2c9595c555fd70a28363489ac03bd5bf9e7c5bdf2890373c3a830ffd7252ce6d
            env:
              OLLAMA_HOST: 0.0.0.0
              OLLAMA_FLASH_ATTENTION: "true"
              OLLAMA_KV_CACHE_TYPE: q8_0
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - "ALL"
            resources:
              requests:
                cpu: 200m
                memory: 3Gi
              limits:
                memory: 12Gi
    defaultPodOptions:
      securityContext:
        fsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
    service:
      ollama:
        controller: ollama
        ports:
          http:
            port: 11434

    route:
      app:
        hostnames: ["{{ .Release.Name }}.${CLUSTER_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      ollama:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: *modelPath
            subPath: models
          - path: /root/.ollama
            subPath: config

      dri:
        type: hostPath
        hostPath: /dev/dri