---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: forgejo
  namespace: renovate
spec:
  discoveryFilters:
    - lab/*
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: |-
        ["pnpm run bundle"]
  image: ghcr.io/renovatebot/renovate:43.171.0@sha256:d99924e0f238edb5ddf4eca2b9d7ac96426caca27bd6768517fed7a4cfdec72b
  parallelism: 5
  provider:
    name: forgejo
    endpoint: https://code.${NEW_PUBLIC_DOMAIN}/api/v1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: renovate-secret
  webhook:
    enabled: true
    authentication:
      enabled: false
