---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: forgejo
  namespace: renovate
spec:
  discoveryFilters:
    - lab/*
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: |-
        ["pnpm run bundle"]
  image: ghcr.io/renovatebot/renovate:43.172.0@sha256:ebc1e7ab4d9b1d37ac88382c4d8175e021589fc1ec4a0f6731f2e06aca730cb2
  parallelism: 5
  provider:
    name: forgejo
    endpoint: https://code.${NEW_PUBLIC_DOMAIN}/api/v1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: renovate-secret
  webhook:
    enabled: true
    authentication:
      enabled: false
