apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:yXHy0i4lXbelqxafCFObeqBW2O9B0/3sNp8Rd9g+eWDQfn5nmQYiOg==,iv:L5voO9EZfpwLuFC8yEdOQrJhqij78c9tS1/UqV7ope4=,tag:w7SvRtMKB55yBZv+0syCaA==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGhnZDdjR1VkYWhrRXJx
            SmRtV1plWUNmL2ZlMTNwbGErRVB4SDRLcUI4CkFMQ0NEVStvUUVMR2hnSTdCUHha
            ek1JcEN6U3lDWkFjSCtIem1JdEltYzgKLS0tIHZtYWVweXdsR0hxSmswQ0hnUTRz
            VDNKWlowS1VXZURES0dJMzRQaWRhQ3cKQFvSLEyCn3WbsD+wCbM4OwuSkHrAr3i1
            fYsM2EhWu/knKGh/zYYqzKpDyV+tjPmvjvI8wWpkZ4RFGTVL8WT/rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T22:04:21Z"
    mac: ENC[AES256_GCM,data:c1ElUNd58D0nGeF+983w1CC0voJqby5+6BO0BmTLn62K+IWPcFnSP/If7ji4Kx41e1hoM8gF5vMUc53HMgH2dv2xGnIk/rT0+Rymk+SK/7JFYFIBg6wERaE84RAODGWfEqczfkt5hwjj8wQcB9CiE3XnSQCbvALyYq7Akz7Rj5I=,iv:NTmAxjqvz9bIZEnF3x77O2W1UF7OZo4+AQShxX5Zz4I=,tag:IGHeBo8HdY+FVVyeGNhMOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
