apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:5VvgSmL7UORi9dezz8mhf9CKVzqyXTOUqyKdWQElE4bMDBAGvxtFeA==,iv:sDtt476vUBDL1o633wRIAUrUtbzk0NA9nu1SzYICEAM=,tag:irOis5K3FlAr606H0DqmDg==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGhnZDdjR1VkYWhrRXJx
            SmRtV1plWUNmL2ZlMTNwbGErRVB4SDRLcUI4CkFMQ0NEVStvUUVMR2hnSTdCUHha
            ek1JcEN6U3lDWkFjSCtIem1JdEltYzgKLS0tIHZtYWVweXdsR0hxSmswQ0hnUTRz
            VDNKWlowS1VXZURES0dJMzRQaWRhQ3cKQFvSLEyCn3WbsD+wCbM4OwuSkHrAr3i1
            fYsM2EhWu/knKGh/zYYqzKpDyV+tjPmvjvI8wWpkZ4RFGTVL8WT/rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T22:15:25Z"
    mac: ENC[AES256_GCM,data:gs5zE+vZ0kYZd8/AhZ+hNi4bUi59XRSAcpWt1pBh+RrksOfNMXPubTibrqsG+OYN7P1qJBUq8tQYuePoY30yEp+KXMXeAn55WsytDjNBICV9yug2PcxNN+nUeQkm1F6ILS930ybcKin0AwjzKCzKA5Vz6Mk7KMi67HCUiNqVUJA=,iv:k4hwKTVE189JMY4LY6O8+nbUWrTEhtiIbSp5AAoW1ho=,tag:bnAEdzXAwOIwhkIBRrbS/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
