apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:5lfIn9XY+uQRr4bF83X1O6jHYdxGOnXA3o1VBaLJ9Voxuarcqcg4HA==,iv:xhACfwWSLW4gTlhk6CyO/D0qmwBDB3PfukGVx+tXV3A=,tag:lYRjvz0deksx6xAkJJkS5Q==,type:str]
sops:
    age:
        - recipient: age1f5ewv724wyshnqllxv25tfsrwyt0g3p2vpwknvg3erx9z3cw5paqyzmysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGhnZDdjR1VkYWhrRXJx
            SmRtV1plWUNmL2ZlMTNwbGErRVB4SDRLcUI4CkFMQ0NEVStvUUVMR2hnSTdCUHha
            ek1JcEN6U3lDWkFjSCtIem1JdEltYzgKLS0tIHZtYWVweXdsR0hxSmswQ0hnUTRz
            VDNKWlowS1VXZURES0dJMzRQaWRhQ3cKQFvSLEyCn3WbsD+wCbM4OwuSkHrAr3i1
            fYsM2EhWu/knKGh/zYYqzKpDyV+tjPmvjvI8wWpkZ4RFGTVL8WT/rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T22:01:01Z"
    mac: ENC[AES256_GCM,data:jCnu6IjA4PAafq2ilpcsxuemillVTz+tHV5aYfv8S4ekAPonMNIskiTCPjhL3r/KsUoiScwQNSWOF95XE6hG95kDc6Ttcfbgsusrg2vXnXTFnE7nXGwXGZZ69QbDq82ZT/ZGTl+A71CFjkY8AynzEa2KAcRfzDJ9VyMgXUy5hxM=,iv:cv8fEZaVwtoalj9mUJzblZDmlZ/jBqj2/w1JwcVJK8M=,tag:qTWdXtQS/xzRyKkUzDIs0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
